project:
  type: website
  output-dir: ../docs/projects

website:
  title: "[GitSAM](../index.html)"
  navbar:
    left:
      - text: 교육
        href: ../guides/index.html
      - text: 연구
        href: index.qmd
      - text: TBTF
        href: ../thesis/index.html
        
    tools:
      - icon: house
        href: https://www.gitsam.com
      - icon: youtube
        href: https://www.youtube.com/@primenumbersam
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/primenumbersam/primenumbersam.github.io
          - text: Report a Bug
            href: mailto:primenumbersam@gmail.com

  sidebar:
    style: floating
    contents:
      - index.qmd
      - section: "분열"
        contents:
        - gilded_age.qmd
        - pricing_equal.qmd
        - dichotomy.qmd
        - corner_solution.qmd
        - market_conditions.qmd
        - market_incomplete.qmd
      - section: "설명? 예측?"
        contents:
        - modern_matthew.qmd
        - capm.qmd
        - capm_industry.qmd
        - structure_cointegration.qmd
        - structure_tfp.qmd
      - section: "비주류경제론-동역학"
        contents:
        - d_overview.qmd
        - d_1_critique.qmd
        - d_2_elementary.qmd
        - d_3_model.qmd
        - d_4_ethics.qmd

author: gitSAM

format:
  html:
    theme: cosmo
    css: ../styles.css
    toc: true
    number-sections: false
    code-fold: true

execute:
  engine: jupyter
  freeze: auto

jupyter: python3