<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.42">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="gitSAM">
<meta name="dcterms.date" content="2025-03-31">

<title>06 Performance – GitSAM</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script><script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-2f5df379a58b258e96c21c0638c20c03.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-ddd961a2510921635943dfbbd19534c4.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>

<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title"><a href="../index.html">GitSAM</a></span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./../guides/index.html"> 
<span class="menu-text">교육</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./../projects/index.html"> 
<span class="menu-text">연구</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">TBTF</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools tools-wide">
    <a href="https://www.gitsam.com" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-house"></i></a>
    <a href="https://www.youtube.com/@primenumbersam" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-youtube"></i></a>
    <div class="dropdown">
      <a href="" title="" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label=""><i class="bi bi-github"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://github.com/primenumbersam/primenumbersam.github.io">
            Source Code
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="mailto:primenumbersam@gmail.com">
            Report a Bug
            </a>
          </li>
      </ul>
    </div>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./4_1_overview.html">Model</a></li><li class="breadcrumb-item"><a href="./4_6_performance.html">06 Performance</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Too Big to Fail?</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./1_intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./2_lit_review.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Literature Review</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">History</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3_1_history.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Recent History</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./3_2_history_nyse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">History of NYSE ME</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">Model</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4_1_overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">01 Overview</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4_2_data.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">02 Data Preprocessing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4_3_ff_compare.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">03 Size Benchmark</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4_4_structure.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">04 Structure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4_5_strategy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">05 Strategy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4_6_performance.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">06 Performance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4_7_robustness.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">07 Robustness</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./4_8_implementation.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">08 Implementation</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./5_conclusion.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Conclusion</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#out-of-sample-evaluation-framework" id="toc-out-of-sample-evaluation-framework" class="nav-link active" data-scroll-target="#out-of-sample-evaluation-framework"><span class="header-section-number">1</span> Out-of-Sample Evaluation Framework</a></li>
  <li><a href="#comparative-distributional-analysis-pre-2010-vs.-post-2010" id="toc-comparative-distributional-analysis-pre-2010-vs.-post-2010" class="nav-link" data-scroll-target="#comparative-distributional-analysis-pre-2010-vs.-post-2010"><span class="header-section-number">2</span> Comparative Distributional Analysis: Pre-2010 vs.&nbsp;Post-2010</a></li>
  <li><a href="#other-benchmark-comparison" id="toc-other-benchmark-comparison" class="nav-link" data-scroll-target="#other-benchmark-comparison"><span class="header-section-number">3</span> Other Benchmark Comparison</a>
  <ul class="collapse">
  <li><a href="#pre-2010-market-dominance-and-diversification" id="toc-pre-2010-market-dominance-and-diversification" class="nav-link" data-scroll-target="#pre-2010-market-dominance-and-diversification"><span class="header-section-number">3.1</span> Pre-2010: Market Dominance and Diversification</a></li>
  <li><a href="#post-2010-structural-convexity-and-breakaway-performance" id="toc-post-2010-structural-convexity-and-breakaway-performance" class="nav-link" data-scroll-target="#post-2010-structural-convexity-and-breakaway-performance"><span class="header-section-number">3.2</span> Post-2010: Structural Convexity and Breakaway Performance</a></li>
  <li><a href="#post-2010-fama-french-portfolios-me-prior" id="toc-post-2010-fama-french-portfolios-me-prior" class="nav-link" data-scroll-target="#post-2010-fama-french-portfolios-me-prior"><span class="header-section-number">3.3</span> Post-2010: Fama-French Portfolios (ME × PRIOR)</a></li>
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation"><span class="header-section-number">3.4</span> Interpretation</a></li>
  </ul></li>
  <li><a href="#risk-adjusted-performance-metrics" id="toc-risk-adjusted-performance-metrics" class="nav-link" data-scroll-target="#risk-adjusted-performance-metrics"><span class="header-section-number">4</span> Risk-Adjusted Performance Metrics</a>
  <ul class="collapse">
  <li><a href="#pre-2010-period" id="toc-pre-2010-period" class="nav-link" data-scroll-target="#pre-2010-period"><span class="header-section-number">4.1</span> Pre-2010 Period</a></li>
  <li><a href="#interpretation-post-2010-period" id="toc-interpretation-post-2010-period" class="nav-link" data-scroll-target="#interpretation-post-2010-period"><span class="header-section-number">4.2</span> Interpretation: Post-2010 Period</a></li>
  </ul></li>
  <li><a href="#drawdown-and-turnover" id="toc-drawdown-and-turnover" class="nav-link" data-scroll-target="#drawdown-and-turnover"><span class="header-section-number">5</span> Drawdown and Turnover</a>
  <ul class="collapse">
  <li><a href="#drawdown-dynamics" id="toc-drawdown-dynamics" class="nav-link" data-scroll-target="#drawdown-dynamics"><span class="header-section-number">5.1</span> Drawdown Dynamics</a></li>
  <li><a href="#tbtf-turnover" id="toc-tbtf-turnover" class="nav-link" data-scroll-target="#tbtf-turnover"><span class="header-section-number">5.2</span> TBTF Turnover</a></li>
  </ul></li>
  <li><a href="#implications" id="toc-implications" class="nav-link" data-scroll-target="#implications"><span class="header-section-number">6</span> Implications</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./4_1_overview.html">Model</a></li><li class="breadcrumb-item"><a href="./4_6_performance.html">06 Performance</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">06 Performance</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>gitSAM </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 31, 2025</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<div id="ca32fe91" class="cell" data-execution_count="1">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sqlite3</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>cons <span class="op">=</span> sqlite3.<span class="ex">connect</span>(database<span class="op">=</span><span class="st">"../../tbtf.sqlite"</span>)</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a>crsp <span class="op">=</span> pd.read_sql_query(</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a>  sql<span class="op">=</span><span class="st">"SELECT * FROM crsp"</span>,</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a>  con<span class="op">=</span>cons,</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>  parse_dates<span class="op">=</span>{<span class="st">"date"</span>}</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="out-of-sample-evaluation-framework" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="out-of-sample-evaluation-framework"><span class="header-section-number">1</span> Out-of-Sample Evaluation Framework</h2>
<p>The TBTF strategy relies on a structurally motivated weighting scheme that reflects not only asset-specific characteristics but also investor preferences toward risk concentration and downside protection. Two key parameters govern this framework:</p>
<ul>
<li><p><strong>Risk aversion parameter (<span class="math inline">\(\eta\)</span>)</strong>:<br>
We employ a CRRA-type (Constant Relative Risk Aversion) transformation in the exponential weighting function, where asset weights are proportional to</p>
<p><span class="math display">\[
  w_i \propto \exp\left(\eta \cdot \hat{r}_i\right).
  \]</span></p>
<p>Here, <span class="math inline">\(\hat{r}_i\)</span> denotes the estimated expected return for asset <span class="math inline">\(i\)</span> based on its in-sample historical performance, typically computed as the average excess return over the past 36 months. This formulation captures the intuition that investors tend to allocate more capital to assets with higher perceived profitability, especially under risk-averse preferences.</p>
<p>The parameter <span class="math inline">\(\eta &gt; 0\)</span> reflects the degree of risk aversion or, equivalently, the strength of capital concentration toward assets with higher expected returns. A higher <span class="math inline">\(\eta\)</span> induces more aggressive overweighting of top-ranked stocks, thereby mimicking the structural capital lock-in observed in real-world markets. In this study, we set <span class="math inline">\(\eta = 3\)</span>, which strikes a balance between diversification and concentration, and is broadly consistent with utility curvature in standard asset pricing and consumption–savings models.</p></li>
<li><p><strong>Tail probability threshold (<span class="math inline">\(p\)</span>) for Omega ratio</strong>:<br>
To quantify downside risk, we use the Omega ratio, which captures the full shape of the return distribution:</p>
<p><span class="math display">\[
\Omega(p) = \frac{\int_p^\infty (1 - F(r)) \, dr}{\int_{-\infty}^p F(r) \, dr}.
\]</span></p>
<p>The threshold <span class="math inline">\(p\)</span> defines the return level below which outcomes are considered losses. We set <span class="math inline">\(p = 0.01\)</span>, corresponding to a 1% monthly return threshold—commonly adopted as the minimum acceptable return (MAR) in institutional risk management. This conservative cutoff captures meaningful left-tail risk while avoiding excessive sensitivity to extreme outliers.</p></li>
</ul>
<p>The strategy is trained on a rolling 36-month in-sample window to estimate optimal exponential weights across the top decile (<code>state = 10</code>) based on lagged market capitalization. Portfolios are rebalanced quarterly (<code>rebalance_freq='3M'</code>) to reflect the long-term stickiness of capital among dominant firms, with structural filtering applied via <span class="math inline">\(\eta = 3\)</span> and <span class="math inline">\(p = 0.01\)</span>.</p>
<p>To rigorously test the strategy’s robustness and economic significance, we conduct fully out-of-sample evaluations over two distinct macro-financial regimes:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>results_pre <span class="op">=</span> tbtf.backtest_pipeline(</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>    crsp<span class="op">=</span>crsp,</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>    in_end<span class="op">=</span><span class="st">'1999-12-31'</span>,</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>    out_end<span class="op">=</span><span class="st">'2009-12-31'</span>,</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>    in_sample_months<span class="op">=</span><span class="dv">36</span>,</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>    rebalance_freq<span class="op">=</span><span class="st">'3M'</span>,</span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a>    weighting_method<span class="op">=</span><span class="st">'exponential'</span>,</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>    top_n<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>    state<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>    eta<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>    p<span class="op">=</span><span class="fl">0.01</span></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>results_post <span class="op">=</span> tbtf.backtest_pipeline(</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    crsp<span class="op">=</span>crsp,</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    in_end<span class="op">=</span><span class="st">'2013-12-31'</span>,</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>    out_end<span class="op">=</span><span class="st">'2023-12-31'</span>,</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    in_sample_months<span class="op">=</span><span class="dv">36</span>,</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a>    rebalance_freq<span class="op">=</span><span class="st">'3M'</span>,</span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a>    weighting_method<span class="op">=</span><span class="st">'exponential'</span>,</span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a>    top_n<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>    state<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>    eta<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>    p<span class="op">=</span><span class="fl">0.01</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div id="ddc12106" class="cell" data-execution_count="2">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Out-of-sample Investment</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co"># 10 years in pre-2010 from 2000-01</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="co"># 10 years in post-2010 from 2004-01</span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sys</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># 현재 경로 기준으로 상위 디렉토리로 경로 추가</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>sys.path.append(os.path.abspath(<span class="st">'../..'</span>))</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> tbtf</span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-12"><a href="#cb3-12" aria-hidden="true" tabindex="-1"></a>results_pre <span class="op">=</span> tbtf.backtest_pipeline(</span>
<span id="cb3-13"><a href="#cb3-13" aria-hidden="true" tabindex="-1"></a>    crsp<span class="op">=</span>crsp,</span>
<span id="cb3-14"><a href="#cb3-14" aria-hidden="true" tabindex="-1"></a>    in_end<span class="op">=</span><span class="st">'1999-12-31'</span>,</span>
<span id="cb3-15"><a href="#cb3-15" aria-hidden="true" tabindex="-1"></a>    out_end<span class="op">=</span><span class="st">'2009-12-31'</span>,</span>
<span id="cb3-16"><a href="#cb3-16" aria-hidden="true" tabindex="-1"></a>    in_sample_months<span class="op">=</span><span class="dv">36</span>,</span>
<span id="cb3-17"><a href="#cb3-17" aria-hidden="true" tabindex="-1"></a>    rebalance_freq<span class="op">=</span><span class="st">'3M'</span>,</span>
<span id="cb3-18"><a href="#cb3-18" aria-hidden="true" tabindex="-1"></a>    weighting_method<span class="op">=</span><span class="st">'exponential'</span>,</span>
<span id="cb3-19"><a href="#cb3-19" aria-hidden="true" tabindex="-1"></a>    top_n<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb3-20"><a href="#cb3-20" aria-hidden="true" tabindex="-1"></a>    state<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb3-21"><a href="#cb3-21" aria-hidden="true" tabindex="-1"></a>    eta<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb3-22"><a href="#cb3-22" aria-hidden="true" tabindex="-1"></a>    p<span class="op">=</span><span class="fl">0.01</span></span>
<span id="cb3-23"><a href="#cb3-23" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-24"><a href="#cb3-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-25"><a href="#cb3-25" aria-hidden="true" tabindex="-1"></a>results_post <span class="op">=</span> tbtf.backtest_pipeline(</span>
<span id="cb3-26"><a href="#cb3-26" aria-hidden="true" tabindex="-1"></a>    crsp<span class="op">=</span>crsp,</span>
<span id="cb3-27"><a href="#cb3-27" aria-hidden="true" tabindex="-1"></a>    in_end<span class="op">=</span><span class="st">'2013-12-31'</span>,</span>
<span id="cb3-28"><a href="#cb3-28" aria-hidden="true" tabindex="-1"></a>    out_end<span class="op">=</span><span class="st">'2023-12-31'</span>,</span>
<span id="cb3-29"><a href="#cb3-29" aria-hidden="true" tabindex="-1"></a>    in_sample_months<span class="op">=</span><span class="dv">36</span>,</span>
<span id="cb3-30"><a href="#cb3-30" aria-hidden="true" tabindex="-1"></a>    rebalance_freq<span class="op">=</span><span class="st">'3M'</span>,</span>
<span id="cb3-31"><a href="#cb3-31" aria-hidden="true" tabindex="-1"></a>    weighting_method<span class="op">=</span><span class="st">'exponential'</span>,</span>
<span id="cb3-32"><a href="#cb3-32" aria-hidden="true" tabindex="-1"></a>    top_n<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb3-33"><a href="#cb3-33" aria-hidden="true" tabindex="-1"></a>    state<span class="op">=</span><span class="dv">10</span>,</span>
<span id="cb3-34"><a href="#cb3-34" aria-hidden="true" tabindex="-1"></a>    eta<span class="op">=</span><span class="dv">3</span>,</span>
<span id="cb3-35"><a href="#cb3-35" aria-hidden="true" tabindex="-1"></a>    p<span class="op">=</span><span class="fl">0.01</span></span>
<span id="cb3-36"><a href="#cb3-36" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb3-37"><a href="#cb3-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-38"><a href="#cb3-38" aria-hidden="true" tabindex="-1"></a><span class="co"># TBTF returns in the out-of-sample</span></span>
<span id="cb3-39"><a href="#cb3-39" aria-hidden="true" tabindex="-1"></a>tbtf_returns_pre2010 <span class="op">=</span> results_pre[<span class="st">'returns'</span>].set_index(<span class="st">'date'</span>)[<span class="st">'portfolio_return'</span>]</span>
<span id="cb3-40"><a href="#cb3-40" aria-hidden="true" tabindex="-1"></a>tbtf_returns_post2010 <span class="op">=</span> results_post[<span class="st">'returns'</span>].set_index(<span class="st">'date'</span>)[<span class="st">'portfolio_return'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>[START] backtest_pipeline 호출됨
[INFO] Total sample: 1996-12-31 00:00:00 to 2009-12-31 00:00:00
[INFO] Total Out-of-sample: 2000-01-31 00:00:00 to 2009-12-31 00:00:00
[DONE] Total returns recorded: 39
[START] backtest_pipeline 호출됨
[INFO] Total sample: 2010-12-31 00:00:00 to 2023-12-31 00:00:00
[INFO] Total Out-of-sample: 2014-01-31 00:00:00 to 2023-12-31 00:00:00
[DONE] Total returns recorded: 39</code></pre>
</div>
</div>
<div id="8f9b893d" class="cell" data-execution_count="3">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>ff3 <span class="op">=</span> pd.read_sql_query(</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a>  sql<span class="op">=</span><span class="st">"SELECT * FROM ff3"</span>,</span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a>  con<span class="op">=</span>cons,</span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>  parse_dates<span class="op">=</span>{<span class="st">"date"</span>}</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a><span class="co"># 날짜를 datetime 형식으로 변환</span></span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>ff3[<span class="st">'date'</span>] <span class="op">=</span> pd.to_datetime(ff3[<span class="st">'date'</span>])</span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a><span class="co"># 인덱스 지정</span></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a>ff3.set_index(<span class="st">'date'</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Pre-2010: 2000–2009</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>market_returns_pre2010 <span class="op">=</span> ff3.loc[<span class="st">'2000-01-31'</span>:<span class="st">'2009-12-31'</span>, <span class="st">'mkt_ret'</span>]</span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Post-2010: 2014–2023</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>market_returns_post2010 <span class="op">=</span> ff3.loc[<span class="st">'2014-01-31'</span>:<span class="st">'2023-12-31'</span>, <span class="st">'mkt_ret'</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="comparative-distributional-analysis-pre-2010-vs.-post-2010" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="comparative-distributional-analysis-pre-2010-vs.-post-2010"><span class="header-section-number">2</span> Comparative Distributional Analysis: Pre-2010 vs.&nbsp;Post-2010</h2>
<p>To assess the structural evolution of market efficiency and capital concentration, we compare the TBTF portfolio’s out-of-sample return distributions against the Fama-French market portfolio return, denoted as <code>mkt_ret</code>. This return series is sourced directly from the Fama-French data library and corresponds to the aggregate U.S. stock market return including dividends.</p>
<p>The comparison is conducted across two distinct macro-financial regimes:</p>
<ul>
<li><strong>Pre-2010 period</strong>: 2000–2009 (trained on data up to 1999)</li>
<li><strong>Post-2010 period</strong>: 2014–2023 (trained on data up to 2013)</li>
</ul>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a>tbtf.plot_return_distribution(tbtf_returns_pre2010, market_returns_pre2010, period_label<span class="op">=</span><span class="st">'pre-2010'</span>)</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>tbtf.plot_return_distribution(tbtf_returns_post2010, market_returns_post2010, period_label<span class="op">=</span><span class="st">'post-2010'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="ba4022db" class="cell quarto-layout-panel" data-execution_count="4" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="4_6_performance_files/figure-html/cell-5-output-1.png" class="img-fluid figure-img"></p>
<figcaption>Monthly Return Distribution of TBTF vs.&nbsp;Market (Pre-2010 vs.&nbsp;Post-2010)</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="4_6_performance_files/figure-html/cell-5-output-2.png" class="img-fluid"></p>
</div>
</div>
</div>
<p>Distributional Shifts from this comparative analysis are as follows:</p>
<ul>
<li>In the pre-2010 window, the TBTF and market portfolios exhibit similar interquartile ranges (IQR), indicating comparable volatility levels. However, the mean return is higher for the market, suggesting that TBTF underperformed not due to risk but due to return inefficiency. TBTF’s distribution is relatively symmetric, while the market shows mild left-skewness. Notably, TBTF exhibits high kurtosis, indicating heavier tails and more frequent extreme outcomes, both positive and negative.</li>
<li>In the post-2010 period, the relationship reverses. While the market portfolio’s standard deviation declines, TBTF not only achieves a higher mean return, but also exhibits superior interquartile positioning—especially in the median and upper quartile. The lower quartile remains similar across both, indicating equivalent downside frequency, but TBTF captures the upside more effectively. In terms of shape, the market distribution becomes more symmetric, whereas TBTF turns left-skewed, reflecting an asymmetric probability mass concentrated just above the loss threshold—consistent with convex return dynamics and infrequent but large outperformance events.</li>
<li>In summary, the roles of the two distributions are structurally inverted across regimes. Pre-2010, TBTF resembled a symmetrical bell-shaped curve with fat tails, while the market was mildly skewed. Post-2010, the market distribution becomes tighter and more symmetric, whereas TBTF becomes more asymmetric and wider, capturing structural convexity in return outcomes. This shift aligns with a regime transition in capital flows and market microstructure following the QE era.</li>
</ul>
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>tbtf.plot_price_level(tbtf_returns_pre2010, market_returns_pre2010, start_date<span class="op">=</span><span class="st">'2000-01-01'</span>, end_date<span class="op">=</span><span class="st">'2009-12-31'</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>tbtf.plot_price_level(tbtf_returns_post2010, market_returns_post2010, start_date<span class="op">=</span><span class="st">'2004-01-01'</span>, end_date<span class="op">=</span><span class="st">'2023-12-31'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div id="bd0f1e4d" class="cell quarto-layout-panel" data-execution_count="5" data-layout-ncol="2">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="4_6_performance_files/figure-html/cell-6-output-1.png" class="img-fluid figure-img"></p>
<figcaption>Price Level Comparison: TBTF vs.&nbsp;Market (Pre-2010 vs.&nbsp;Post-2010)</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: center;">
<p><img src="4_6_performance_files/figure-html/cell-6-output-2.png" class="img-fluid"></p>
</div>
</div>
</div>
<div id="5e3fd7a4" class="cell" data-execution_count="6">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>pre_index <span class="op">=</span> pd.read_sql_query(</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>  sql<span class="op">=</span><span class="st">"SELECT * FROM pre_index"</span>,</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>  con<span class="op">=</span>cons,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>  parse_dates<span class="op">=</span>{<span class="st">"date"</span>}</span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>post_index <span class="op">=</span> pd.read_sql_query(</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  sql<span class="op">=</span><span class="st">"SELECT * FROM post_index"</span>,</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  con<span class="op">=</span>cons,</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  parse_dates<span class="op">=</span>{<span class="st">"date"</span>}</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>post_ff <span class="op">=</span> pd.read_sql_query(</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>  sql<span class="op">=</span><span class="st">"SELECT * FROM post_ff"</span>,</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a>  con<span class="op">=</span>cons,</span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>  parse_dates<span class="op">=</span>{<span class="st">"date"</span>}</span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="other-benchmark-comparison" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="other-benchmark-comparison"><span class="header-section-number">3</span> Other Benchmark Comparison</h2>
<p>To further contextualize the performance of the TBTF strategy, we compare it against a wide set of benchmark portfolios, including major U.S. equity indices and Fama-French style-sorted portfolios. Each comparison is presented as a paired figure showing the <strong>monthly return distribution (left)</strong> and the <strong>cumulative price level evolution (right)</strong>.</p>
<div id="2b6c7265" class="cell" data-execution_count="7">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a>tbtf.plot_benchmark_comparison(tbtf_returns_pre2010, pre_index, period_label<span class="op">=</span><span class="st">'pre-2010'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="4_6_performance_files/figure-html/cell-8-output-1.png" class="img-fluid figure-img"></p>
<figcaption>TBTF vs.&nbsp;Benchmarks (Pre-2010)</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="4_6_performance_files/figure-html/cell-8-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<div id="3f3e826a" class="cell" data-execution_count="8">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>tbtf.plot_benchmark_comparison(tbtf_returns_post2010, post_index, period_label<span class="op">=</span><span class="st">'post-2010'</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a>tbtf.plot_benchmark_comparison(tbtf_returns_post2010, post_ff, period_label<span class="op">=</span><span class="st">'post-2010 (FF)'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="4_6_performance_files/figure-html/cell-9-output-1.png" class="img-fluid figure-img"></p>
<figcaption>TBTF vs.&nbsp;Benchmarks (Post-2010)</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="4_6_performance_files/figure-html/cell-9-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="4_6_performance_files/figure-html/cell-9-output-3.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="4_6_performance_files/figure-html/cell-9-output-4.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="4_6_performance_files/figure-html/cell-9-output-5.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="4_6_performance_files/figure-html/cell-9-output-6.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="4_6_performance_files/figure-html/cell-9-output-7.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="4_6_performance_files/figure-html/cell-9-output-8.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="4_6_performance_files/figure-html/cell-9-output-9.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="4_6_performance_files/figure-html/cell-9-output-10.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<section id="pre-2010-market-dominance-and-diversification" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="pre-2010-market-dominance-and-diversification"><span class="header-section-number">3.1</span> Pre-2010: Market Dominance and Diversification</h3>
<p>In the pre-2010 sample, TBTF underperforms all major benchmarks both in terms of average monthly returns and cumulative price levels:</p>
<ul>
<li>Compared to the <strong>Dow Jones Industrial Average (^DJI)</strong> and the <strong>Nasdaq 100 (^NDX)</strong>, TBTF lags significantly in mean returns, with its average return even falling below zero. This underperformance is visible in both the return histogram and the flattened price trajectory.</li>
<li>The <strong>shape of the return distributions</strong> further illustrates this divergence. While ^DJI displays a concentrated bell-shaped curve reflecting strong diversification benefits across sectors, TBTF’s distribution is wider and flatter, and ^NDX’s distribution appears even flatter and fatter-tailed—consistent with its tech-heavy composition and lower effective diversification.</li>
<li>These findings imply that during this regime, the structural capital lock-in emphasized by TBTF was not yet rewarded, and sectoral diversification still played a dominant role in driving returns.</li>
</ul>
</section>
<section id="post-2010-structural-convexity-and-breakaway-performance" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="post-2010-structural-convexity-and-breakaway-performance"><span class="header-section-number">3.2</span> Post-2010: Structural Convexity and Breakaway Performance</h3>
<p>Post-2010, the TBTF strategy decisively outperforms all benchmark portfolios, not only in cumulative performance but also in distributional characteristics:</p>
<ul>
<li>Most strikingly, <strong>TBTF’s return distribution exhibits bi-modality</strong>, a rare phenomenon in empirical asset returns. Both modes are positive, with the second, larger mode emerging after recovering from a brief period of negative returns during late 2021 to early 2022. This distributional structure reflects a convex outcome space where moderate and large gains dominate.</li>
<li><strong>DIA</strong>, which tracks the 30 blue-chip constituents of ^DJI, displays a symmetric but left-skewed return profile and a relatively muted price level curve. By contrast, TBTF rapidly diverges post-2019, widening the performance gap year by year.</li>
<li><strong>QQQ</strong>, representing the Nasdaq 100 ETF, initially tracks TBTF closely between 2014 and 2020. However, since 2021, TBTF begins to <strong>consistently outperform QQQ</strong>, suggesting a regime shift where <strong>capital dominance surpasses even tech momentum</strong>.</li>
<li><strong>SPY</strong>, representing the broader S&amp;P 500, sits between DIA and QQQ in both return level and distributional shape. Its distribution approximates a classic symmetric bell curve, but lacks the convexity and upside concentration observed in TBTF.</li>
<li>The <strong>return distribution of SPY</strong> is unimodal and centered, offering a useful contrast to the dual-modal, right-tilted structure of TBTF.</li>
</ul>
</section>
<section id="post-2010-fama-french-portfolios-me-prior" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="post-2010-fama-french-portfolios-me-prior"><span class="header-section-number">3.3</span> Post-2010: Fama-French Portfolios (ME × PRIOR)</h3>
<p>We also include value-weighted and equal-weighted Fama-French 3x2 portfolios constructed from top 20% market cap stocks (ME5) sorted by prior return (PRIOR1–5):</p>
<ul>
<li>Among value-weighted portfolios, <strong>PRIOR5 (ff_b)</strong> performs best, followed by <strong>PRIOR3 (ff_m)</strong> and <strong>PRIOR1 (ff_s)</strong>. This gradient suggests a standard momentum pattern. However, <strong>TBTF outpaces all of them</strong>, with its <strong>price level evolving geometrically</strong>, while FF portfolios show <strong>only linear growth trends</strong> over the same horizon.</li>
<li>Among equal-weighted portfolios, performance is more muted. Notably, <strong>ff_e_s</strong> (equal-weighted ME5 × PRIOR1) performs slightly better than its value-weighted counterpart, suggesting that <strong>in low-momentum groups, idiosyncratic selection beats size dominance</strong>.</li>
<li>Yet again, <strong>none of the FF portfolios, whether value- or equal-weighted, come close to TBTF’s performance</strong>, emphasizing that TBTF’s structural logic—built on capital persistence and lock-in rather than factor exposure—offers a fundamentally different return engine.</li>
</ul>
</section>
<section id="interpretation" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="interpretation"><span class="header-section-number">3.4</span> Interpretation</h3>
<p>The above comparisons reinforce the hypothesis that <strong>post-2010 capital markets have undergone a structural realignment</strong>. In this new regime, traditional sources of diversification and factor exposure lose explanatory power, while the concentration of capital into a select few entities generates persistent excess returns. The TBTF strategy captures this realignment directly through its construction, thereby achieving outperformance not through luck or timing, but by aligning itself with the <strong>new architecture of capital allocation</strong> in the post-QE world.</p>
</section>
</section>
<section id="risk-adjusted-performance-metrics" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="risk-adjusted-performance-metrics"><span class="header-section-number">4</span> Risk-Adjusted Performance Metrics</h2>
<p>To benchmark the performance of the TBTF strategy against traditional market indices, we compute a suite of risk-adjusted performance metrics over both the <strong>pre-2010</strong> and <strong>post-2010</strong> periods. These include:</p>
<ul>
<li><strong>Sharpe ratio</strong>: Mean excess return normalized by standard deviation.</li>
<li><strong>Sortino ratio</strong>: Return per unit of downside deviation, focusing on losses.</li>
<li><strong>Omega ratio</strong>: A distribution-sensitive metric measuring the ratio of gains above a threshold to losses below it.</li>
<li><strong>Maximum drawdown</strong>: Largest peak-to-trough loss during the sample period.</li>
<li><strong>Expected CRRA utility</strong>: A model-based expected utility under constant relative risk aversion.</li>
</ul>
<p>The final metric—Expected CRRA Utility—provides a theoretically grounded welfare measure, widely used in academic finance. Unlike Sharpe or Sortino ratios, CRRA utility reflects higher-order moments of the return distribution, such as skewness and kurtosis, which are especially relevant for TBTF’s left-skewed but convex payoff structure. For a CRRA coefficient <span class="math inline">\(\gamma &gt; 0\)</span>, utility is computed as:</p>
<p><span class="math display">\[
\mathbb{E}[U(W)] = \frac{1}{1 - \gamma} \cdot \mathbb{E}\left[(1 + r)^{1 - \gamma}\right],
\]</span></p>
<p>where <span class="math inline">\(r\)</span> is the gross monthly return. We set <span class="math inline">\(\gamma = 3\)</span> to reflect moderate risk aversion, consistent with our strategy design.</p>
<p>Tables below report the performance metrics for selected portfolios, sorted by <strong>Expected CRRA Utility</strong>.</p>
<section id="pre-2010-period" class="level3" data-number="4.1">
<h3 data-number="4.1" class="anchored" data-anchor-id="pre-2010-period"><span class="header-section-number">4.1</span> Pre-2010 Period</h3>
<div id="670128e1" class="cell" data-execution_count="9">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>returns_dict_pre2010 <span class="op">=</span> {</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'TBTF'</span>: tbtf_returns_pre2010,</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'DJI'</span>: pre_index[<span class="st">'^DJI'</span>],</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'NDX'</span>: pre_index[<span class="st">'^NDX'</span>]</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Risk-Adjusted Performance Comparison (Pre-2010)"</span></span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a>tbtf.generate_performance_table(returns_dict_pre2010).sort_values(by<span class="op">=</span><span class="st">'Expected CRRA'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="9">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Annualized Return</th>
<th data-quarto-table-cell-role="th">Annualized Volatility</th>
<th data-quarto-table-cell-role="th">Sharpe Ratio</th>
<th data-quarto-table-cell-role="th">Sortino Ratio</th>
<th data-quarto-table-cell-role="th">Omega Ratio</th>
<th data-quarto-table-cell-role="th">Max Drawdown</th>
<th data-quarto-table-cell-role="th">Calmar Ratio</th>
<th data-quarto-table-cell-role="th">Expected CRRA</th>
<th data-quarto-table-cell-role="th">Fisher Skewness</th>
<th data-quarto-table-cell-role="th">Pearson Skewness</th>
<th data-quarto-table-cell-role="th">Excess Kurtosis</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Portfolio</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">DJI</td>
<td>0.053029</td>
<td>0.159515</td>
<td>0.405245</td>
<td>0.536194</td>
<td>0.764380</td>
<td>-0.492970</td>
<td>0.107571</td>
<td>0.002087</td>
<td>-0.611944</td>
<td>-0.246797</td>
<td>1.035444</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">NDX</td>
<td>0.088080</td>
<td>0.300315</td>
<td>0.433556</td>
<td>0.638719</td>
<td>1.026011</td>
<td>-0.810698</td>
<td>0.108647</td>
<td>-0.000878</td>
<td>-0.249061</td>
<td>-0.162229</td>
<td>0.519681</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">TBTF</td>
<td>-0.102382</td>
<td>0.180976</td>
<td>-0.504393</td>
<td>-0.693212</td>
<td>0.398926</td>
<td>-0.312157</td>
<td>-0.327984</td>
<td>-0.011923</td>
<td>-0.194323</td>
<td>0.078361</td>
<td>0.463931</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The risk-adjusted performance metrics for the pre-2010 period reveal that the TBTF strategy significantly underperforms relative to traditional benchmarks such as the Dow Jones Industrial Average (DJI) and Nasdaq 100 (NDX). While both benchmarks deliver positive annualized returns—5.3% for DJI and 8.8% for NDX—TBTF produces a <strong>negative average return of -10.2%</strong>, resulting in uniformly negative values for all performance ratios.</p>
<ul>
<li><strong>Sharpe and Sortino ratios</strong> for TBTF are both negative, indicating that the strategy failed to compensate for volatility and downside risk during this period.</li>
<li>The <strong>Omega ratio</strong> of TBTF (0.40) is substantially lower than that of NDX (1.03) and DJI (0.76), further emphasizing poor downside-adjusted performance.</li>
<li><strong>Maximum drawdown</strong>, surprisingly, is less severe for TBTF (-31.2%) than for NDX (-81.1%), though this is largely due to TBTF’s failure to experience large upswings, not resilience in downturns.</li>
<li>The <strong>Expected CRRA utility</strong> for TBTF is negative (-0.0119), in stark contrast to the positive values for DJI (+0.0021). This indicates that, for a moderately risk-averse investor (<span class="math inline">\(\gamma = 3\)</span>), TBTF would have been <strong>strictly dominated</strong> by holding a benchmark index.</li>
<li>In terms of distribution shape, TBTF displays <strong>near-zero skewness</strong> and <strong>moderate excess kurtosis</strong>, suggesting symmetric but fat-tailed returns. This is consistent with the earlier observation that pre-2010 TBTF returns resembled a bell curve with heavy tails, whereas NDX was left-skewed and more extreme in both tails.</li>
</ul>
<p>Taken together, these results indicate that during the pre-QE, industrial-cycle-driven market regime, the structural logic behind TBTF—capital lock-in and size dominance—did not translate into superior returns. Instead, diversification (as in DJI) and tech momentum (as in NDX) dominated portfolio performance.</p>
</section>
<section id="interpretation-post-2010-period" class="level3" data-number="4.2">
<h3 data-number="4.2" class="anchored" data-anchor-id="interpretation-post-2010-period"><span class="header-section-number">4.2</span> Interpretation: Post-2010 Period</h3>
<div id="14792d51" class="cell" data-execution_count="10">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>returns_dict_post2010 <span class="op">=</span> {</span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>    <span class="st">'TBTF'</span>: tbtf_returns_post2010,</span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>    <span class="st">'DIA'</span>: post_index[<span class="st">'DIA'</span>],</span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>    <span class="st">'QQQ'</span>: post_index[<span class="st">'QQQ'</span>],</span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>    <span class="st">'SPY'</span>: post_index[<span class="st">'SPY'</span>],</span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a>    <span class="st">'VTI'</span>: post_index[<span class="st">'VTI'</span>]</span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="co">#| tbl-cap: "Risk-Adjusted Performance Comparison (Post-2010)"</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a>tbtf.generate_performance_table(returns_dict_post2010).sort_values(by<span class="op">=</span><span class="st">'Expected CRRA'</span>, ascending<span class="op">=</span><span class="va">False</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="10">
<div>


<table class="dataframe caption-top table table-sm table-striped small" data-quarto-postprocess="true" data-border="1">
<thead>
<tr class="header">
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th">Annualized Return</th>
<th data-quarto-table-cell-role="th">Annualized Volatility</th>
<th data-quarto-table-cell-role="th">Sharpe Ratio</th>
<th data-quarto-table-cell-role="th">Sortino Ratio</th>
<th data-quarto-table-cell-role="th">Omega Ratio</th>
<th data-quarto-table-cell-role="th">Max Drawdown</th>
<th data-quarto-table-cell-role="th">Calmar Ratio</th>
<th data-quarto-table-cell-role="th">Expected CRRA</th>
<th data-quarto-table-cell-role="th">Fisher Skewness</th>
<th data-quarto-table-cell-role="th">Pearson Skewness</th>
<th data-quarto-table-cell-role="th">Excess Kurtosis</th>
</tr>
<tr class="even">
<th data-quarto-table-cell-role="th">Portfolio</th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
<th data-quarto-table-cell-role="th"></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td data-quarto-table-cell-role="th">TBTF</td>
<td>0.358215</td>
<td>0.211433</td>
<td>1.568884</td>
<td>2.209493</td>
<td>2.169813</td>
<td>-0.210497</td>
<td>1.701760</td>
<td>0.021408</td>
<td>-0.352156</td>
<td>0.054055</td>
<td>1.127887</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">QQQ</td>
<td>0.169477</td>
<td>0.178377</td>
<td>0.971665</td>
<td>1.612117</td>
<td>1.241137</td>
<td>-0.330703</td>
<td>0.512476</td>
<td>0.010306</td>
<td>-0.192792</td>
<td>-0.303277</td>
<td>0.010333</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">SPY</td>
<td>0.109163</td>
<td>0.148966</td>
<td>0.772762</td>
<td>1.143819</td>
<td>0.975512</td>
<td>-0.247979</td>
<td>0.440211</td>
<td>0.006722</td>
<td>-0.344475</td>
<td>-0.344606</td>
<td>0.541203</td>
</tr>
<tr class="even">
<td data-quarto-table-cell-role="th">VTI</td>
<td>0.108100</td>
<td>0.153839</td>
<td>0.746852</td>
<td>1.077633</td>
<td>0.974996</td>
<td>-0.256668</td>
<td>0.421165</td>
<td>0.006514</td>
<td>-0.355191</td>
<td>-0.254563</td>
<td>0.720072</td>
</tr>
<tr class="odd">
<td data-quarto-table-cell-role="th">DIA</td>
<td>0.096274</td>
<td>0.145753</td>
<td>0.705438</td>
<td>1.085427</td>
<td>0.913413</td>
<td>-0.231042</td>
<td>0.416694</td>
<td>0.005855</td>
<td>-0.171162</td>
<td>-0.164886</td>
<td>0.948737</td>
</tr>
</tbody>
</table>

</div>
</div>
</div>
<p>The post-2010 performance metrics tell a dramatically different story. In this regime—characterized by sustained quantitative easing, historically low interest rates, and capital concentration—the TBTF strategy not only outperforms all benchmark portfolios in raw returns, but does so <strong>decisively across all risk-adjusted dimensions</strong>.</p>
<ul>
<li><strong>Annualized return</strong> for TBTF reaches <strong>35.8%</strong>, more than twice that of QQQ (16.9%) and over three times that of SPY, VTI, and DIA (all below 11%).</li>
<li>The <strong>Sharpe ratio</strong> of TBTF (1.57) is by far the highest, indicating a return per unit of volatility unmatched by any benchmark. More notably, the <strong>Sortino ratio</strong> (2.21) and <strong>Omega ratio</strong> (2.17) reveal TBTF’s <strong>asymmetric protection against downside</strong>, a signature feature of its convex payoff structure.</li>
<li><strong>Maximum drawdown</strong> is relatively modest at -21.0%, despite the high return level, and the <strong>Calmar ratio</strong> (1.70) reflects this efficiency. By comparison, QQQ suffers a deeper drawdown (-33.1%) with only a third of the Calmar ratio.</li>
<li>Crucially, the <strong>Expected CRRA utility</strong> for TBTF is <strong>+0.0214</strong>, more than double that of QQQ (+0.0103), and significantly above other diversified portfolios (SPY: +0.0067, VTI: +0.0065, DIA: +0.0059). For a moderately risk-averse investor (<span class="math inline">\(\gamma = 3\)</span>), TBTF represents a clear welfare-maximizing choice.</li>
<li>From a distributional perspective, TBTF shows <strong>mild negative skewness (Fisher: -0.35)</strong> and <strong>positive excess kurtosis (1.13)</strong>, consistent with earlier evidence of <strong>bimodality and tail concentration</strong>. In contrast, SPY and VTI are more symmetric but exhibit thinner tails, which limits their upside potential.</li>
<li>QQQ, while historically strong, demonstrates a <strong>flattened distribution with lower Omega and Sortino ratios</strong>, suggesting diminished downside protection relative to TBTF in recent years.</li>
</ul>
<p>These results reinforce the view that the post-2010 market environment systematically rewarded capital dominance over traditional diversification or momentum strategies. TBTF’s success is not just statistically significant, but economically meaningful across every major dimension of portfolio evaluation—returns, risk, asymmetry, drawdowns, and investor utility.</p>
</section>
</section>
<section id="drawdown-and-turnover" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="drawdown-and-turnover"><span class="header-section-number">5</span> Drawdown and Turnover</h2>
<p>In this section, we evaluate the <strong>downside risk exposure</strong> and <strong>implementation feasibility</strong> of the TBTF strategy. Two key dimensions are analyzed:</p>
<ul>
<li><strong>Maximum Drawdown</strong>: Measures the largest peak-to-trough decline in cumulative return over the evaluation period.</li>
<li><strong>Portfolio Turnover</strong>: Assesses the degree of rebalancing required, with lower turnover implying lower transaction costs and higher implementability.</li>
</ul>
<section id="drawdown-dynamics" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="drawdown-dynamics"><span class="header-section-number">5.1</span> Drawdown Dynamics</h3>
<blockquote class="blockquote">
<p>While TBTF suffered deeper losses than ^DJI during the 2008 crisis, its post-2010 drawdown profile proved significantly more resilient than traditional style portfolios and benchmark ETFs, with a rapid recovery trajectory by 2023.</p>
</blockquote>
<div id="0e8121ee" class="cell" data-execution_count="11">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.dates <span class="im">as</span> mdates</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> compute_drawdown(return_series: pd.Series) <span class="op">-&gt;</span> pd.Series:</span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>    cumulative <span class="op">=</span> (<span class="dv">1</span> <span class="op">+</span> return_series).cumprod()</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>    peak <span class="op">=</span> cumulative.cummax()</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a>    drawdown <span class="op">=</span> (cumulative <span class="op">-</span> peak) <span class="op">/</span> peak</span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> drawdown</span>
<span id="cb13-9"><a href="#cb13-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-10"><a href="#cb13-10" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_drawdown(tbtf_returns_raw, benchmark_df, title<span class="op">=</span><span class="st">"Drawdown Profile"</span>):</span>
<span id="cb13-11"><a href="#cb13-11" aria-hidden="true" tabindex="-1"></a>    plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">4</span>))</span>
<span id="cb13-12"><a href="#cb13-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-13"><a href="#cb13-13" aria-hidden="true" tabindex="-1"></a>    <span class="co"># --- TBTF 처리 ---</span></span>
<span id="cb13-14"><a href="#cb13-14" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="bu">isinstance</span>(tbtf_returns_raw, pd.DataFrame):</span>
<span id="cb13-15"><a href="#cb13-15" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> <span class="st">'date'</span> <span class="kw">in</span> tbtf_returns_raw.columns:</span>
<span id="cb13-16"><a href="#cb13-16" aria-hidden="true" tabindex="-1"></a>            tbtf_returns_raw <span class="op">=</span> tbtf_returns_raw.set_index(pd.to_datetime(tbtf_returns_raw[<span class="st">'date'</span>]))</span>
<span id="cb13-17"><a href="#cb13-17" aria-hidden="true" tabindex="-1"></a>        tbtf_returns <span class="op">=</span> tbtf_returns_raw.select_dtypes(include<span class="op">=</span><span class="st">'number'</span>).iloc[:, <span class="dv">0</span>]</span>
<span id="cb13-18"><a href="#cb13-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">elif</span> <span class="bu">isinstance</span>(tbtf_returns_raw, pd.Series):</span>
<span id="cb13-19"><a href="#cb13-19" aria-hidden="true" tabindex="-1"></a>        tbtf_returns <span class="op">=</span> tbtf_returns_raw</span>
<span id="cb13-20"><a href="#cb13-20" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb13-21"><a href="#cb13-21" aria-hidden="true" tabindex="-1"></a>        <span class="cf">raise</span> <span class="pp">TypeError</span>(<span class="st">"tbtf_returns_raw must be DataFrame or Series."</span>)</span>
<span id="cb13-22"><a href="#cb13-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-23"><a href="#cb13-23" aria-hidden="true" tabindex="-1"></a>    tbtf_returns.index <span class="op">=</span> pd.to_datetime(tbtf_returns.index)</span>
<span id="cb13-24"><a href="#cb13-24" aria-hidden="true" tabindex="-1"></a>    tbtf_drawdown <span class="op">=</span> compute_drawdown(tbtf_returns)</span>
<span id="cb13-25"><a href="#cb13-25" aria-hidden="true" tabindex="-1"></a>    plt.plot(tbtf_drawdown.index, tbtf_drawdown.values, label<span class="op">=</span><span class="st">'TBTF'</span>, color<span class="op">=</span><span class="st">'black'</span>, linewidth<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb13-26"><a href="#cb13-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-27"><a href="#cb13-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># --- 벤치마크 DataFrame 처리 ---</span></span>
<span id="cb13-28"><a href="#cb13-28" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> <span class="st">'date'</span> <span class="kw">in</span> benchmark_df.columns:</span>
<span id="cb13-29"><a href="#cb13-29" aria-hidden="true" tabindex="-1"></a>        benchmark_df <span class="op">=</span> benchmark_df.set_index(pd.to_datetime(benchmark_df[<span class="st">'date'</span>]))</span>
<span id="cb13-30"><a href="#cb13-30" aria-hidden="true" tabindex="-1"></a>    <span class="cf">else</span>:</span>
<span id="cb13-31"><a href="#cb13-31" aria-hidden="true" tabindex="-1"></a>        benchmark_df.index <span class="op">=</span> pd.to_datetime(benchmark_df.index)</span>
<span id="cb13-32"><a href="#cb13-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-33"><a href="#cb13-33" aria-hidden="true" tabindex="-1"></a>    benchmark_df <span class="op">=</span> benchmark_df.select_dtypes(include<span class="op">=</span><span class="st">'number'</span>)  <span class="co"># 숫자만</span></span>
<span id="cb13-34"><a href="#cb13-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-35"><a href="#cb13-35" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> col <span class="kw">in</span> benchmark_df.columns:</span>
<span id="cb13-36"><a href="#cb13-36" aria-hidden="true" tabindex="-1"></a>        series <span class="op">=</span> benchmark_df[col].reindex(tbtf_returns.index)</span>
<span id="cb13-37"><a href="#cb13-37" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> series.isna().<span class="bu">all</span>():</span>
<span id="cb13-38"><a href="#cb13-38" aria-hidden="true" tabindex="-1"></a>            <span class="cf">continue</span>  <span class="co"># 완전히 비어있으면 skip</span></span>
<span id="cb13-39"><a href="#cb13-39" aria-hidden="true" tabindex="-1"></a>        drawdown <span class="op">=</span> compute_drawdown(series)</span>
<span id="cb13-40"><a href="#cb13-40" aria-hidden="true" tabindex="-1"></a>        plt.plot(drawdown.index, drawdown.values, label<span class="op">=</span>col, alpha<span class="op">=</span><span class="fl">0.7</span>)</span>
<span id="cb13-41"><a href="#cb13-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-42"><a href="#cb13-42" aria-hidden="true" tabindex="-1"></a>    <span class="co"># --- x축 날짜 포맷 ---</span></span>
<span id="cb13-43"><a href="#cb13-43" aria-hidden="true" tabindex="-1"></a>    ax <span class="op">=</span> plt.gca()</span>
<span id="cb13-44"><a href="#cb13-44" aria-hidden="true" tabindex="-1"></a>    ax.xaxis.set_major_locator(mdates.YearLocator())</span>
<span id="cb13-45"><a href="#cb13-45" aria-hidden="true" tabindex="-1"></a>    ax.xaxis.set_major_formatter(mdates.DateFormatter(<span class="st">'%Y'</span>))</span>
<span id="cb13-46"><a href="#cb13-46" aria-hidden="true" tabindex="-1"></a>    plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb13-47"><a href="#cb13-47" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-48"><a href="#cb13-48" aria-hidden="true" tabindex="-1"></a>    <span class="co"># --- 마무리 ---</span></span>
<span id="cb13-49"><a href="#cb13-49" aria-hidden="true" tabindex="-1"></a>    plt.title(title)</span>
<span id="cb13-50"><a href="#cb13-50" aria-hidden="true" tabindex="-1"></a>    plt.ylabel(<span class="st">"Drawdown"</span>)</span>
<span id="cb13-51"><a href="#cb13-51" aria-hidden="true" tabindex="-1"></a>    plt.xlabel(<span class="st">"Date"</span>)</span>
<span id="cb13-52"><a href="#cb13-52" aria-hidden="true" tabindex="-1"></a>    plt.legend()</span>
<span id="cb13-53"><a href="#cb13-53" aria-hidden="true" tabindex="-1"></a>    plt.grid(<span class="va">True</span>)</span>
<span id="cb13-54"><a href="#cb13-54" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb13-55"><a href="#cb13-55" aria-hidden="true" tabindex="-1"></a>    plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<section id="pre-2010-period-20002009" class="level4" data-number="5.1.1">
<h4 data-number="5.1.1" class="anchored" data-anchor-id="pre-2010-period-20002009"><span class="header-section-number">5.1.1</span> Pre-2010 Period (2000–2009)</h4>
<div id="de2cd4eb" class="cell" data-execution_count="12">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>plot_drawdown(results_pre[<span class="st">'returns'</span>], pre_index, title<span class="op">=</span><span class="st">"Drawdown Profile (Pre-2010)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="4_6_performance_files/figure-html/cell-13-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>During the first decade, the TBTF strategy underperformed the Dow Jones Industrial Average (^DJI) in terms of drawdown resilience. While TBTF, ^DJI, and ^NDX all exhibited relatively similar patterns prior to the 2008 Global Financial Crisis, the drawdown plot reveals that TBTF experienced a sharper decline during the crisis episode. This suggests that TBTF’s concentrated exposure to the largest-cap firms provided limited diversification benefit during systemic tail events, particularly in contrast to the more balanced composition of the ^DJI.</p>
</section>
<section id="post-2010-period-20142023" class="level4" data-number="5.1.2">
<h4 data-number="5.1.2" class="anchored" data-anchor-id="post-2010-period-20142023"><span class="header-section-number">5.1.2</span> Post-2010 Period (2014–2023)</h4>
<div id="37c7b89e" class="cell" data-execution_count="13">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>plot_drawdown(results_post[<span class="st">'returns'</span>], post_index, title<span class="op">=</span><span class="st">"Drawdown Profile (Post-2010)"</span>)</span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>plot_drawdown(results_post[<span class="st">'returns'</span>], post_ff, title<span class="op">=</span><span class="st">"Drawdown Profile (Post-2010)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="4_6_performance_files/figure-html/cell-14-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="4_6_performance_files/figure-html/cell-14-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>In contrast, during the second decade, TBTF demonstrated superior drawdown performance relative to all benchmark ETFs, particularly until late 2021. The strategy maintained shallow drawdowns through several volatility cycles, including the COVID-19 shock and inflation-driven rate adjustments, reflecting its structural bias toward persistent market leaders.</p>
<p>However, in late 2021, TBTF experienced a notable drawdown phase, closely mirrored by the QQQ, indicating common exposure to high-growth tech stocks. Despite this synchronized decline, both TBTF and QQQ rebounded strongly by 2023, surpassing prior peaks.</p>
<p>Notably, the Fama-French style-sorted portfolios (ME×PRIOR) exhibited deeper and more persistent drawdowns throughout the post-2010 period. These portfolios consistently underperformed TBTF in drawdown magnitude, highlighting the limitations of conventional size- and momentum-based constructions in capturing the structural dominance embedded in TBTF’s selection mechanism.</p>
</section>
</section>
<section id="tbtf-turnover" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="tbtf-turnover"><span class="header-section-number">5.2</span> TBTF Turnover</h3>
<div id="5174a023" class="cell" data-execution_count="14">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb16"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.dates <span class="im">as</span> mdates</span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> plot_turnover(turnover_df, title<span class="op">=</span><span class="st">"TBTF Turnover Over Time"</span>):</span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>    df <span class="op">=</span> turnover_df.copy()</span>
<span id="cb16-6"><a href="#cb16-6" aria-hidden="true" tabindex="-1"></a>    df[<span class="st">'rebalance_date'</span>] <span class="op">=</span> pd.to_datetime(df[<span class="st">'rebalance_date'</span>])</span>
<span id="cb16-7"><a href="#cb16-7" aria-hidden="true" tabindex="-1"></a>    df.set_index(<span class="st">'rebalance_date'</span>, inplace<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb16-8"><a href="#cb16-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-9"><a href="#cb16-9" aria-hidden="true" tabindex="-1"></a>    plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>, <span class="dv">3</span>))</span>
<span id="cb16-10"><a href="#cb16-10" aria-hidden="true" tabindex="-1"></a>    plt.plot(df.index, df[<span class="st">'turnover'</span>], marker<span class="op">=</span><span class="st">'o'</span>, color<span class="op">=</span><span class="st">'darkgreen'</span>, linewidth<span class="op">=</span><span class="fl">1.5</span>)</span>
<span id="cb16-11"><a href="#cb16-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-12"><a href="#cb16-12" aria-hidden="true" tabindex="-1"></a>    <span class="co"># x축 날짜 format</span></span>
<span id="cb16-13"><a href="#cb16-13" aria-hidden="true" tabindex="-1"></a>    ax <span class="op">=</span> plt.gca()</span>
<span id="cb16-14"><a href="#cb16-14" aria-hidden="true" tabindex="-1"></a>    ax.xaxis.set_major_locator(mdates.YearLocator())</span>
<span id="cb16-15"><a href="#cb16-15" aria-hidden="true" tabindex="-1"></a>    ax.xaxis.set_major_formatter(mdates.DateFormatter(<span class="st">'%Y'</span>))</span>
<span id="cb16-16"><a href="#cb16-16" aria-hidden="true" tabindex="-1"></a>    plt.xticks(rotation<span class="op">=</span><span class="dv">45</span>)</span>
<span id="cb16-17"><a href="#cb16-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb16-18"><a href="#cb16-18" aria-hidden="true" tabindex="-1"></a>    plt.title(title)</span>
<span id="cb16-19"><a href="#cb16-19" aria-hidden="true" tabindex="-1"></a>    plt.ylabel(<span class="st">"Turnover (sum of abs weight changes)"</span>)</span>
<span id="cb16-20"><a href="#cb16-20" aria-hidden="true" tabindex="-1"></a>    plt.xlabel(<span class="st">"Rebalance Date"</span>)</span>
<span id="cb16-21"><a href="#cb16-21" aria-hidden="true" tabindex="-1"></a>    plt.grid(<span class="va">True</span>)</span>
<span id="cb16-22"><a href="#cb16-22" aria-hidden="true" tabindex="-1"></a>    plt.tight_layout()</span>
<span id="cb16-23"><a href="#cb16-23" aria-hidden="true" tabindex="-1"></a>    plt.show()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div id="30c79e06" class="cell" data-execution_count="15">
<details class="code-fold">
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pre-2010 turnover plot</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>plot_turnover(results_pre[<span class="st">'turnover'</span>].iloc[:<span class="op">-</span><span class="dv">1</span>], title<span class="op">=</span><span class="st">"TBTF Turnover (Pre-2010)"</span>)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Post-2010 turnover plot</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>plot_turnover(results_post[<span class="st">'turnover'</span>].iloc[:<span class="op">-</span><span class="dv">1</span>], title<span class="op">=</span><span class="st">"TBTF Turnover (Post-2010)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="4_6_performance_files/figure-html/cell-16-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="4_6_performance_files/figure-html/cell-16-output-2.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>The TBTF strategy rebalances quarterly, yet maintains a remarkably steady turnover profile across both subperiods, highlighting its structural persistence and practical implementability.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Period</th>
<th>Mean Turnover</th>
<th>Std Dev</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Pre-2010</td>
<td>0.22</td>
<td>0.12</td>
</tr>
<tr class="even">
<td>Post-2010</td>
<td>0.15</td>
<td>0.10</td>
</tr>
</tbody>
</table>
<p>This low and stable turnover suggests that, although the strategy updates weights every three months, the <strong>actual reallocation of capital is limited</strong>. This is particularly meaningful given TBTF’s concentrated structure: the top 10 stocks by market capitalization.</p>
<p>To further explore the internal mechanics of turnover, we examine the group-rank positions of stocks entering and exiting the portfolio:</p>
<ul>
<li>The average <strong><code>max_diff_group_rank</code></strong> is approximately <strong>1–2</strong>, indicating that stocks removed from the TBTF portfolio were typically ranked <strong>9th or 10th</strong> before exit.<br>
</li>
<li>The average <strong><code>min_diff_group_rank</code></strong> is approximately <strong>3–3.5</strong>, suggesting that newly entering stocks typically displaced members ranked around <strong>6th or 7th</strong>.</li>
</ul>
<p>This pattern implies a <strong>core–fringe structure</strong> within the TBTF portfolio:<br>
the <strong>top-ranked firms (1st–5th)</strong> exhibit strong persistence, while changes are concentrated at the margin of the selection, reducing both instability and turnover-related costs.</p>
</section>
</section>
<section id="implications" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="implications"><span class="header-section-number">6</span> Implications</h2>
<p>The TBTF strategy consistently delivers strong out-of-sample performance, characterized by high risk-adjusted returns, stable drawdowns, and low turnover. These patterns persist across both pre- and post-2010 market regimes and cannot be explained by conventional size or momentum factors.</p>
<p>What distinguishes TBTF is not merely statistical outperformance but its reflection of <strong>a persistent capital hierarchy</strong>, in which dominant firms retain market share through institutional mechanisms rather than pure productivity or risk-taking.</p>
<p>Whereas traditional models explain return premia through exposure to priced risk, TBTF accumulates return through insulation from risk—via passive flows, platform effects, and embedded expectations. In this sense, <strong>market power does not demand a premium—it neutralizes the need for one</strong>.</p>
<p>This invites a reframing of modern asset pricing:<br>
&gt; <em>Return without risk is no longer a puzzle, but a feature of financial capitalism.</em></p>
<p>Readers seeking formal modeling of regime persistence and capital asymmetry are referred to <a href="./4_4_structure.html">Section 4</a>. Here, we have focused on empirical validation, leaving latent structure estimation to the structural section.</p>
<p>In the following section, we assess whether TBTF’s performance is <strong>robust to alternative specifications</strong>: selection cutoffs, rebalancing intervals, weighting schemes, and estimation windows. This stress-testing is essential to distinguish true structural effects from parameter-driven artifacts.</p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>