project:
  type: website
  output-dir: ../docs/paper-tbtf

website:
  title: "[GitSAM](../index.html)"
  navbar:
    left:
      - text: "Papers"
        menu:
          - text: "Working"
            href: ../papers/index.html
          - text: "TBTF"
            href: index.html
      - text: "Books"
        menu:
          - text: "gitsam 기초통계학"
            href: ../book-gitsam-stats/index.html
          - text: "AI 응용 선형대수학"
            href: https://primenumbersam.github.io/
      - text: "Apps"
        href: https://github.com/primenumbersam/
      - text: "스터디클럽"
        href: https://www.gitsam.com

    tools:
      - icon: shop
        href: https://laroe.co.kr/
      - icon: youtube
        href: https://www.youtube.com/@primenumbersam
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/primenumbersam/primenumbersam.github.io
          - text: Report a Bug
            href: mailto:primenumbersam@gmail.com

  sidebar:
    style: floating
    contents:
      - index.qmd
      - 1_intro.qmd
      - 2_lit_review.qmd
      - section: "History"
        contents:
        - 3_1_history.qmd
        - 3_2_history_nyse.qmd
      - section: "Model"
        contents:
        - 4_1_overview.qmd
        - 4_2_data.qmd
        - 4_3_ff_compare.qmd
        - 4_4_structure.qmd
        - 4_5_strategy.qmd
        - 4_6_performance.qmd
        - 4_7_robustness.qmd
        - 4_8_implementation.qmd
      - 5_conclusion.qmd
      - tbtf_data_plot.qmd

author: gitSAM
date: '2025-03-31'
bibliography: references.bib

format:
  html:
    theme: cosmo
    css: ../styles.css
    toc: true
    number-sections: true
    code-fold: true

execute:
  engine: jupyter
  freeze: auto

jupyter: python3