project:
  type: website
  output-dir: ../docs/paper-tbtf

website:
  favicon: ../assets/favicon.png
  navbar:
    logo: ../assets/logo-nav.png
    logo-href: ../index.html
    search: true
    left:
      - text: "Apps"
        href: https://github.com/primenumbersam/
      - text: "Books"
        menu:
          - text: "AI 기초 수학"
            href: ../book-ai-math/index.html
          - text: "AI 기초 통계학"
            href: ../book-ai-stats/index.html
          - text: "AI 응용 선형대수학"
            href: ../book-ai-algebra/index.html
          - text: "AI 응용 미적분학"
            href: ../book-ai-calculus/index.html
      - text: "Papers"
        menu:
          - text: "Working"
            href: ../papers/index.html
          - text: "Thesis"
            href: index.html
    tools:
      - icon: github
        href: https://github.com/primenumbersam/primenumbersam.github.io

  page-footer:
    border: false
    background: light
    left: "© 2025 · GITSAM · All rights reserved"
    right:
      - icon: youtube
        href: https://www.youtube.com/@primenumbersam
      - icon: instagram
        href: https://instagram.com/primenumbersam
      - icon: shop
        href: https://laroe.co.kr/

  sidebar:
    style: floating
    contents:
      - index.qmd
      - 1_intro.qmd
      - 2_lit_review.qmd
      - section: "History"
        contents:
        - 3_1_history.qmd
        - 3_2_history_nyse.qmd
        - 3_3_history_survivorship.qmd
      - section: "Model"
        contents:
        - 4_1_overview.qmd
        - 4_2_data.qmd
        - 4_3_ff_compare.qmd
        - 4_4_structure.qmd
        - 4_5_strategy.qmd
        - 4_6_performance.qmd
        - 4_7_robustness.qmd
        - 4_8_implementation.qmd
      - 5_conclusion.qmd


author: gitSAM
date: '2025-03-31'
bibliography: references.bib

format:
  html:
    include-in-header: "../analytics.html"
    theme:
      light: cosmo
      dark: cyborg
    appearance: toogle
    toc: true
    number-sections: true
    code-fold: true

execute:
  engine: jupyter
  freeze: auto

jupyter: python3