project:
  type: website
  output-dir: ../docs/book-gitsam-stats

website:
  title: "[GitSAM](../index.html)"
  navbar:
    left:
      - text: "Papers"
        menu:
          - text: "Working"
            href: ../papers/index.html
          - text: "TBTF"
            href: ../paper-tbtf/index.html
      - text: "Books"
        menu:
          - text: "gitsam 기초통계학"
            href: index.qmd
          - text: "AI 응용 선형대수학"
            href: ../book-ai-algebra/index.html
          - text: "gitsam Han(恨)"
            href: ../book-gitsam-han/index.html
      - text: "Apps"
        href: https://github.com/primenumbersam/
      - text: "스터디클럽"
        href: https://www.gitsam.com

    tools:
      - icon: shop
        href: https://laroe.co.kr/
      - icon: youtube
        href: https://www.youtube.com/@primenumbersam
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/primenumbersam/primenumbersam.github.io
          - text: Report a Bug
            href: mailto:primenumbersam@gmail.com

  sidebar:
    style: "floating"
    contents:
      - index.qmd
      - section: "통계 데이터 (Statistical Data)"
        contents:
        - 1-1.qmd
        - 1-2.qmd
        - 1-3.qmd
        - 1-4.qmd
      - section: "데이터 탐색 (Exploration)"
        contents:
        - 2-1.qmd
        - 2-2.qmd
      - section: "데이터와 가설의 연결고리 (Probability)"
        contents:
        - 3-1.qmd
        - 3-2.qmd
        - 3-3.qmd
        - 3-4.qmd
      - section: "데이터 활용 (Exploitation)"
        contents:
        - 4-1.qmd
        - 4-2.qmd
        - 4-3.qmd
        - 4-4.qmd
        - 4-5.qmd
      - section: "모형계수 추정법 (Estimation)"
        contents:
        - 5-1.qmd
        - 5-2.qmd
        - 5-3.qmd
      - section: "가설 점정 (Hypothesis Test)"
        contents:
        - 6-1.qmd
        - 6-2.qmd
        - 6-3.qmd
        - 6-4.qmd

author: gitSAM

date: "2025-04-30"

license: "CC BY-NC-SA 4.0"

format:
  html:
    theme: cosmo
    css: ../styles.css
    toc: true
    number-sections: true
    code-fold: true

execute:
  engine: jupyter
  freeze: auto

jupyter: python3