project:
  type: website
  output-dir: docs

website:
  title: "GitSAM"
  navbar:
    left:
      - href: index.qmd
        text: Formats
      - text: "Projects"
        menu: 
          - href: projects/gilded_age/gilded_age.qmd
            text: The New Gilded Age
          - href: projects/pricing_equal/pricing_equal.qmd
            text: Pricing Equal Opportunity
          - href: projects/correlation_crypto/correlation_crypto.qmd
            text: Correlation in Crypto
          - href: projects/dichotomy/dichotomy.qmd
            text: Dichotomy
    tools:
      - icon: house
        href: https://www.gitsam.com
      - icon: youtube
        href: https://www.youtube.com/@primenumbersam
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/primenumbersam/primenumbersam.github.io
          - text: Report a Bug
            href:  mailto:primenumbersam@gmail.com
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



