project:
  type: website
  output-dir: docs

website:
  title: "GitSAM"
  navbar:
    left:
      - about.qmd
      - text: "Projects"
        menu: 
          - href: projects/gilded_age/gilded_age.qmd
            text: The New Gilded Age
          - href: projects/pricing_equal/pricing_equal.qmd
            text: Pricing Equal Opportunity
          - href: projects/dichotomy/dichotomy.qmd
            text: Distinct Dichotomy
          - href: projects/pareto_index/pareto_index.qmd
            text: Estimating Pareto Index
          - href: projects/corner_solution/corner_solution.qmd
            text: Heading to Corner Solutions
          - href: time-series/joint_covariance_stationary.qmd
            text: Stationary process
          - href: time-series/tfp.qmd
            text: TFP?
      - text: "한글"
        menu: 
          - href: projects/correlation_crypto/correlation_crypto.qmd
            text: 암호화폐들의 상관관계
          - href: time-series/yield_curve.qmd
            text: 채권투자와 금리
          - href: time-series/labor_decoupling.qmd
            text: 노동 기여와 분배
          - href: time-series/indicator_growth.qmd
            text: 경제성장 지표

    tools:
      - icon: house
        href: https://www.gitsam.com
      - icon: youtube
        href: https://www.youtube.com/@primenumbersam
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/primenumbersam/primenumbersam.github.io
          - text: Report a Bug
            href:  mailto:primenumbersam@gmail.com
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



