project:
  type: website
  output-dir: docs

website:
  title: "githubpages"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: about.qmd
        text: another about

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



