project:
  type: website
  output-dir: docs

website:
  title: "githubpages"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: about.qmd
        text: another about
    tools:
      - icon: twitter
        href: https://twitter.com
      - icon: github
        menu:
          - text: Source Code
            href:  https://code.com
          - text: Report a Bug
            href:  https://bugs.com
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



