project:
  type: website
  output-dir: docs

website:
  favicon: /assets/favicon.png
  navbar:
    logo: /assets/logo-nav.png
    search: true
    left:
      - text: "Apps"
        href: https://github.com/primenumbersam/
      - text: "Books"
        menu:
          - text: "AI 기초 수학"
            href: book-ai-math/index.html
          - text: "AI 기초 통계학"
            href: book-ai-stats/index.html
          - text: "AI 응용 선형대수학"
            href: book-ai-algebra/index.html
          - text: "AI 응용 미적분학"
            href: book-ai-calculus/index.html
      - text: "Papers"
        menu:
          - text: "Working"
            href: papers/index.html
          - text: "Thesis"
            href: paper-tbtf/index.html
    tools:
      - icon: github
        href: https://github.com/primenumbersam/primenumbersam.github.io

  page-footer:
    border: false
    background: light
    left: "© 2025 · GITSAM · All rights reserved"
    right:
      - icon: youtube
        href: https://www.youtube.com/@primenumbersam
      - icon: instagram
        href: https://instagram.com/
      - icon: shop
        href: https://laroe.co.kr/

format:
  html:
    include-in-header: "analytics.html"
    css: styles.css
    theme:
      light: cosmo
      dark: cyborg
    appearance: toogle

execute:
  engine: jupyter
  freeze: auto

jupyter: python3