project:
  type: website
  output-dir: docs

website:
  title: "GitSAM"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects/gilded_age/gilded_age.qmd
        text: The New Gilded Age
    tools:
      - icon: youtube
        href: https://www.youtube.com/@primenumbersam
      - icon: github
        menu:
          - text: Source Code
            href:  https://github.com/primenumbersam/primenumbersam.github.io
          - text: Report a Bug
            href:  mailto:primenumbersam@gmail.com
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



