project:
  type: website
  output-dir: docs

execute:
  engine: jupyter
  freeze: auto

jupyter: python3

website:
  title: "GitSAM"
  navbar:
    left:
      - about.qmd
      - text: "TBTF"
        href: thesis/index.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "Drafts"
        href: drafts/index.qmd
      - text: "Guides"
        href: guides/index.qmd
    tools:
      - icon: house
        href: https://www.gitsam.com
      - icon: youtube
        href: https://www.youtube.com/@primenumbersam
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/primenumbersam/primenumbersam.github.io
          - text: Report a Bug
            href: mailto:primenumbersam@gmail.com
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
