project:
  type: website
  output-dir: ../docs/book-ai-calculus

website:
  favicon: ../assets/favicon.png
  navbar:
    logo: ../assets/logo-nav.png
    logo-href: ../index.html
    search: true
    left:
      - text: "Apps"
        href: https://github.com/primenumbersam/
      - text: "Books"
        menu:
          - text: "AI 기초 수학"
            href: ../book-ai-math/index.html
          - text: "AI 기초 통계학"
            href: ../book-ai-stats/index.html
          - text: "AI 응용 선형대수학"
            href: ../book-ai-algebra/index.html
          - text: "AI 응용 미적분학"
            href: index.html
      - text: "Papers"
        menu:
          - text: "Working"
            href: ../papers/index.html
          - text: "Thesis"
            href: ../paper-tbtf/index.html
    tools:
      - icon: github
        href: https://github.com/primenumbersam/primenumbersam.github.io

  page-footer:
    border: false
    background: light
    left: "© 2025 · GITSAM · All rights reserved"
    right:
      - icon: youtube
        href: https://www.youtube.com/@primenumbersam
      - icon: instagram
        href: https://instagram.com/primenumbersam
      - icon: shop
        href: https://laroe.co.kr/

  sidebar:
    style: "floating"
    contents:
      - index.qmd
      - section: "섹션 1"
        contents:
        - 1-1.qmd
      - section: "섹션 2"
        contents:
        - 2-1.qmd
        - 2-2.qmd

license: "CC BY-NC-SA 4.0"

format:
  html:
    include-in-header: "../analytics.html"
    theme:
      light: cosmo
      dark: cyborg
    appearance: toogle
    toc: true
    number-sections: true
    code-fold: true

execute:
  engine: jupyter
  freeze: auto

jupyter: python3