---
title: 수포자 산수문제 21
---

## 수포자를 위한 도입

- 기초 수학시험 : 공무원 입시, 미국 SAT, GMAT, GRE 등등
- 팁: 여러 분야에서 “비율”로 정의된 단어들의 뜻을 알기.
    - 분수, 상대적 비율, 곱셈 이항연산
    - $y=ax$ 의 의미
        - $a:=$ 알려진 “비율” 상수
        - $x:=$ 관측한 숫자**들**, 독립변수
        - $y$ = 몰라서 추정할 숫자**들**, 종속변수
    - ‘퍼센트’ 라는 비율:
        - 6은 2의 300%
        - $y$는 $x$의 $p$% : $y=\frac{p}{100}x \iff \frac{y}{x}=\frac{p}{100}=a$
    - (사건의) ‘확률’ 이라는 비율:
        - A 사건에 부여된 수학적 확률 = (A 경우의 수) / (전체 경우의 수)
    - (산술) 평균 이라는 대표값:
        - 집단내 원소 좌표 모두에 똑같은 가중치 (1/n)를 부여해서 더한 값
    - 과학의 물리 (역학, 화학 등)는 물질과 운동의 성질에 대한 양 (quantity)을 관찰하여 다룬다. 질량, 좌표, 주기 등.
    - 물체의 **속력** = 물체가 원점에서 움직인 거리 / 원점으로부터 걸린 시간.
        - 거리 : = **위치** 좌표계에서 물체의 좌표와 원점 ($x_0$)의 수학적 차이
        - 시간 : = **시간** 좌표계에서 물체의 좌표와 시작점 ($t_0$)의 수학적 차이
    - 가성비 = 단위 비용 당 얻는 수익
    - 출력 = 시스템이 일을 하는 능률 = 단위 시간 당 시스템이 하는 일의 양
    - (A+B) 엔진의 출력 = A엔진의 출력 + B엔진의 출력
    - 덧셈에 대해 **보존**되는 물리량 = 개수, 질량, 에너지, 출력, 압력, 전압 (볼트), 전류 (암페어) 등
    - 물질의 질량은 합쳐도 변하지 않는다 (질량 보존의 법칙). 질량 (혼합물 속 용질) = 질량 (혼합전 A 속의 용질) + 질량 (혼합전 B 속의 용질)
    - 액체인 소금물 (solution)은 액체인 물 (solvent)에 고체인 소금 (solute)이 “녹은” 상태이다. 액체인 용액 (solution)은, 액체인 용매(solvent)와 고체인 용질(solute)이 합쳐졌을 때 용질이 화학적 침전물 (precipitation) 없이 용매에 녹아서 (solved) 용질의 부피량 (volume)이 없어진 물리적 상태이다. 따라서 부피(용액) = 부피(용매) + 부피 (용질) = 부피 (용매) + 0. 그러나 일반적으로 용질이 용매에 ‘녹지 않은’ 혼합물 (mixture)의 부피는, 부피 (혼합물) = 부피 (구성물 A) + 부피 (구성물 B). 물과 기름을 섞은 것의 부피는 원래 부피를 합해야 한다.
- 소금물 문제: 2%의 소금물과 10%의 소금물을 적당히 섞어서, 7%의 소금물 800g 을 만들고자 한다. 이때, 넣어야하는 2%의 소금물과 10%의 소금물의 양의 차이는?
    
    선형 연립방정식
    
    - 부피의 총합: $800=X+Y$
    - 용질의 총합: $2X+10Y=7\cdot 800$
    - $X=300, Y=500$ 이므로, $|X-Y|=200g$
    
    빨리 푸는 방법 (균형 내분점) : 숫자 2와 숫자 10 의 위치에 적당한 가중치을 곱해서 (i.e. 전체 질량을 분배하여) 숫자 7의 위치가 전체 질량 800g의 무게중심이 되도록 만든다. |7-2| = **5** 이고, |7-10| = 3 이다. 숫자 2와 숫자 10의 위치를 양 끝점으로 가지는 시소의 중심이 숫자 7의 위치가 되려면, 숫자 2에 300 g을 태우고, 숫자 10에 500g을 태우면 된다. 따라서 두 무게 사이의 차이는 200g이다. 



## 20 문제

- 아파트의 오늘 판매 가격 $x=200$은 어제 판매가격 $y$에 비해 $p=3$ 퍼센트 내린 가격이다. 그렇다면 그 물건의 어제 가격 (원) $y$는?
    
    $x=y-y(p/100) \iff 200=y-y(3/100)=0.97y$. Thus, $y=\frac{200}{0.97} \approx 206$
    
- 아파트의 내일 판매가격 $y$은 오늘 판매가격 $x=200$ 보다 $p=200$ 퍼센트 내린 가격이 된다. 그렇다면 내일 그 아파트의 판매가격 $y$는?
    
    $y=x-x(200/100)=x(1-2)=-200$. 따라서 그 물건을 사면, 파는 사람이 사는 사람에게 200원을 공짜로 줘야한다.
    
- 어떤 물건의 정가는 원가의 1.5배라고 한다. 그런데 물건이 팔리지 않아 20% 할인 행사를 하여 36불에 팔리고 있다. 그렇다면 물건의 원가는 할인 가격보다 얼마나 싼가?
    
    할인가격 36불은 원가(x)의 1.5배 가격을 20% 내린 가격이다. 36불 - x?
    
    $36=1.5x(1-0.2)$. Thus,  $36-x= 36-30=6$ 불
    
- A를 포함한 직원 9명의 평균 나이가 37세이다. A가 퇴사하고 남은 직원들의 평균나이가 38세 때, A의 나이는? (평균)
    
    29세
    
- 현재 어머니의 나이는 45세이고, 아들의 나이는 13세이다. 어머니 나이가 아들 나이의 3배가 되는 때는 몇 년 후인가?
    
    3년후
    
- 2024년은 윤년. 아기가 2025년 5월 6일 일요일에 태어났다. 아기의 10번째 생일은 무슨 요일?
    
    금요일
    
- 2017년 6월 15일이 목요일이라면, 그 해 12월 25일은 무슨 요일?
    
    월요일
    
- 8시와 9시 사이에 시침과 분침이 정확히 일치하는 시각은?
    
    8시 480/11분
    
- n시와 (n+1)시 사이에 시침과 분침이 정확히 일치하는 시각은?
    
    n시 60n/11분
    
- 3시에서 4시 사이에 시침과 분침이 서로 반대 방향으로 일직선 위에 있을 때의 시각은?
    
    3시 540/11분
    

- 회사 직원의 전체 남녀 비율은 5:7, 생산직 직원의 남녀 비율은 3:4, 사무직 직원의 남녀 비율은 1:2이다. 총 직원의 수가 120명일 때, 생산직 직원의 수는?
    
    생산직 = 105명 (빨리 푸는 힌트: 사람의 수는 항상 자연수이므로, 소인수분해 이용) = 5*7×(1+2)
    
- 어떤 회사의 작년 직원수는 200명이었다. 올해는 작년에 비해 남자 직원은 15% 증가하고, 여자 직원은 10% 감소하여, 전체 학생수가 5명 증가하였다. 작년의 남학생 수는?
    
     100명
    
- 어떤 회사의 작년 직원수는 600명이었는데, 올해는 작년에 비해 남자 직원수는 4% 감소하고 여자 직원수는 14% 증가하여 전체적으로 직원수가 2% 증가하였다. 올해 여학생 수는?
    
    228명
    
- 남자가 16명, 여자가 14명 근무하고 있는 회사에서, 남자 9명, 여자 6명이 안경을 쓰고 있다. 이 회사에 근무하는 사람 중에서 임의로 선택한 한 사람이 안경을 쓰고 있을 때, 그 사람이 남자일 확률은?
    
    9/15
    
- 부품 A의 생산율은 60%, 부품 B의 생산율은 40%이다. A의 불량률은 5%이고, B의 불량률은 3%이다. 생산된 불량품이 부품 A일 확률은? (조건부 확률)
    
    5/7
    
- 어떤 일을 끝내는데, A가 혼자서 하면 3시간이 걸리고, B가 혼자서 하면 6시간이 걸린다. 이 일을 두 사람이 함께하여 마무리 하는데 걸리는 시간은? (단, 일의 능률은 변함이 없다고 가정한다)
    
    2시간
    
- A가 먼저 4일 동안 한 후, 나머지를 B가 6일 동안 하면 끝낼 수 있는 일이 있다. 이 일을 A가 2일 동안 한 후, 나머지를 B가 9일 동안 하여 끝냈다. B가 혼자서 이 일을 마치려면 며칠이 걸리겠는가? (단, 일의 능률은 변함이 없다고 가정한다)
    
    12일
    
- 속력이 일정한 기차가 120m 인 다리를 완전히 통과하는 데는 5초가 걸리고, 300m인 터널을 완전히 통과하는 데는 10초가 걸린다. 이때 기차의 길이는?
    
    60m
    
- 길이가 100m인 두 열차가 각각 시속 120km로 마주 보며 접근하고 있다. 두 열차가 만나서 완전히 스치고 지나갈 때까지 걸리는 시간은?
    
    3초
    
- 집에서 주유소를 거쳐 거래처로 출장을 가는 데 총 거리는 110km 이다. 집에서 1시에 출발해서 주유소까지는 시속 40km의 속력으로 주행하다가 주유소에 사람이 많은 것을 보고 주유를 하지 않고 그때부터 지금까지의 1.5배 속력으로 주행하여 거래처에 도착해서 시계를 보니 3시 30분이었다. 주유소에서 거래처까지의 거리는?
    
    30 km