---
title: 노무현 (1946-2009, 대한민국)
---

대한민국 제16대 대통령 노무현 (Roh Moo-hyun).

> 저는 진보적 자유주의자이고 싶습니다.

---

**Roh Moo-hyun**:  

> 정의가 무너진 사회에서는 어떠한 번영도 있을 수 없다." (검찰개혁 연설 中)

**Han**:  
그가 생각했던 '번영'은 단순한 경제적 성장(growth)이 아니었습니다.  
모든 사람들이 존엄을 지키며 살아갈 수 있는 경제적 발전(development)이었습니다.  
그런데 저는  
노무현 대통령님께서 꿈꾸셨던 '정의 (justice)'는  
과연 무엇이었는지 궁금했습니다. 

---

**Roh Moo-hyun**:  

> 제가 생각하는 이상적인 사회는  
더불어 사는 사람  
모두가 먹는 것 입는 것 이런 걱정 좀 안하고  
더럽고 아니꼬운 꼬라지 좀 안보고  
그래서 하루하루가 좀 신명나게 이어지는 그런 세상이라고 생각을 합니다.  
만일 이런 세상이 좀 지나친 욕심이라면  
적어도 살기가 힘이 들어서  
아니면 분하고 서러워서 스스로 목숨을 끊는  
그런 일은 좀 없는 세상 이런 것이라고 생각합니다.  
옛날에는 생활고로 일가족이 집단 자살하는 일이 많이 있었습니다.  
지금은 그런 일은 거의 없는 것 같은데  
그런데도 스스로 목숨을 끊는 사람은 늘어만 갑니다.  
(중략)  
월남전 생각이 납니다.  
월남전에 대해서 온 세계가 비난을 하고 있었을 때  
정부는 슬그머니 여론을 이렇게 조성했습니다.  
월남전에 참여해서 벌어온 돈으로 우리 경제가 발전되었노라고.  
이렇게 사람을 속이려 했습니다.  
이런 발상이야 말로  
돈이면 무슨 짓이든 다 할 수 있다는 것입니다.  
내 나라 백성 몇만 명 죽일 수 있다는 끔찍한 발상입니다.  
저는 이렇게 묻겠습니다.  
그런 발상을 가진 사람들에게  
파이를 크게 해야 된다고 생각하는 사람들에게,  
니네들 자식 데려다가 죽이란 말이야!  
춥고 배고프고 힘없는 노동자들 말고,  
바로 당신들 자식 데려다가 현장에서 죽이면서 이 나라 경제를 발전시킵시다!  
(1988.7.8. 제 142회 임시국회 대정부질의 中)

**Han**:  
저는 '모두'라는 단어에서  
민주주의의 핵심적 가치,  
민주주의 사회의 '정의 (justice)'를  
깨달을 수 있었습니다. 

그것은 바로  
**'모든' 인간의 존엄적 가치는 평등하다**였습니다. 
그리고 이 당연한 '정의'를,  
조금씩 현실 사회에 반영해 나가는 노력이었습니다.  

사후적 결과를 정당화하기 위해  
돈의 목적인 인간 생명을  
돈의 도구처럼 취급하려 했던,  
왜곡된 능력주의와 성장주의를 바꾸려는  
아름다운 용기였습니다. 

불공정한 구조 위에서 성장을 추구하는 것은 '탁상공론'이지만,  
불공정한 구조 자체를 바꾸려는 용기는 민주주의의 실천입니다.

결코 불의에 굽히지 않고,  
결코 불의에 굴복하지 않고,  
결코 불의와 타협하지 않고,  
조금이라도 바꾸려는 용기를 가져야,  
조금이라도 바꾸어 나갈 수 있다는 희망을 가져야,  
조금이라도 바꾸어 나갈 수 있을 것이기 때문입니다. 

---

**Roh Moo-hyun**:  

> 결코 굽히지 않는,  
결코 굴복하지 않는,  
결코 타협하지 않는 살아있는 영혼이!  
깨끗한 영혼을 가지고 이 정치판에서 살아남는 증거를 여러분들에게 보여줌으로 해서  
우리 아이들에게 결코 불의와 타협하지 않아도 성공할 수 있다는 하나의 증거를  
꼭 남기고 싶었습니다.  
(1995년 부산시장 선거 연설 中)

**Han**:  
절대 다수의 사람들은  
태어날 때부터  
옳고 그름을 구별할 수 있는  
작은 등불 같은  
'양심'을 지니고 태어나는 것일지도 모릅니다.   
시간이 흐르며  
그 '양심'이 '도덕'이라 불리고  
그 도덕이 '윤리'가 되고,  
그 윤리가 '법'이 되었을지도 모릅니다.  
그래서  
'법치주의'란  
단순히 위법만 피해갈 수 있으면 되는  
그런 제도가 아니라,  
우리 모두의 자연적 양심을 믿어도 되는  
우리 모두의 약속이 되어야 합니다.  

노무현 대통령님께서는  
"양심은 살아 있다"는 역사를  
미래 세대에게 증명해 보이려고 하셨습니다. 

그는  
그 증거를 남기기 위해  
굽히지 않으셨고,  
굴복하지 않으셨고,  
타협하지 않으셨습니다.

저는 그의 그 살아 있는 영혼을 기억하려합니다.  
그리고 저 또한 그렇게 살아가려 합니다.

---

**Roh Moo-hyun**:  

> 광주에서 콩이면 부산에서도 콩이고 대구에서도 콩인,  
옳고 그름을 중심으로 해서 인물과  
정책을 중심으로 해서 그렇게 정치를 해나갈 수 있는,  
그래서 국민들에게 봉사할 수 있는  
새로운 정치를 이 노무현이 열겠습니다.  
(2000.4.1. 16대 총선 거리유세 中)

**Han**:  
진실과 정의의 실천은  
과거나 출신이나 지역을 넘어서야 하기에,  
도덕성과 양심을 갖춘 사람만이  
국민에게 봉사하는 지도자가 될 수 있을 것입니다.

---

**Roh Moo-hyun**:  

> 조선 건국 이래로 600년 동안 우리는  
권력에 맞서서 권력을 한 번도 바꾸어 보지 못했습니다.  
비록 그것이 정의라 할지라도  
비록 그것이 진리라 할지라도  
권력이 싫어하는 말을 했던 사람은  
또는 진리를 내세워서 권력에 저항했던 사람들은  
전부 죽임을 당했습니다. 그 자손들까지 멸문지화를 당했습니다. 패가망신했습니다.  
600년 동안 한국에서 부귀영화를 누리고자 하는 사람은 모두  
권력에 줄을 서서 손바닥을 비비고 머리를 조아려야 했습니다.  
그저 밥이나 먹고살고 싶으면  
세상에서 어떤 부정이 저질러져도  
어떤 불의가 눈앞에서 벌어지고 있어도  
강자가 부당하게 약자를 짓밟고 있어도  
모른 척하고 고개 숙이고 외면했어야 됐습니다.  
눈 감고 귀를 막고 비굴한 삶을 사는 사람만이  
목숨을 부지하면서 밥이라도 먹고 살 수 있었던 우리 600년의 역사!  

제 어머니가 제게 남겨 주었던 제 가훈은  
"야 이 놈아. 모난 돌이 정 맞는다.  
계란으로 바위치기다.  
바람 부는 대로 물결치는 대로 눈치 보며 살아라." 였습니다.  
80년대, 시위하다가 감옥 간 우리의...  
정의롭고 혈기 넘치는 우리 젊은 아이들에게  
그 어머니들이 간곡히 간곡히 타일렀던 그들의 가훈 역시  
"야 이 놈아. 계란으로 바위치기다. 고만 둬라. 너는 뒤로 빠져라." 였습니다. 

이 비겁한 교훈을 가르쳐야 했던 우리 600년의 역사, 
이 역사를 청산해야 합니다.  
권력에 맞서서  
당당하게 권력을 한 번 쟁취하는 우리의 역사가 이루어져야만이  
이제 비로소 우리의 젊은이들이 떳떳하게 정의를 얘기할 수 있고  
떳떳하게 불의에 맞설 수 있는  
새로운 역사를 만들어 낼 수 있습니다!  
(2001.12.10. 제16대 대통령 민주당 후보 국민 경선 출마 연설문 中)

**Han**:  
우리 대한민국 "600년의 역사",  
이 역사에는  
공익을 위해 권한을 사용한 지도자들이 아니라,  
권한에 내재된 한계와 의무를 망각하고  
사익을 위해 권한을 남용한 엘리트들의  
권한의 혜택과 권리만을 취하며  
사회의 구조를 왜곡해 왔던 역사가  
분명하게 기록되어 있습니다.

하지만 그 왜곡된 역사 속에는 분명히,  
살아남기 위해 어쩔 수 없이 고개를 숙이고 눈을 감아야 했던  
더 많은 시민들도 존재합니다.  
"모난 돌이 정 맞는다"는 왜곡된 구조 속에서도,  
"계란으로 바위치기" 같던 불균형한 구조 속에서도,  
꺼지지 않은 촛불을 품은  
양심적 시민들도 존재합니다.  

바로 그 사실 자체가  
희망의 증거가 될 수 있습니다.  

저는 믿습니다.  
숨죽여 살아야 했던 사람들의  
민주주의를 향한 위대한 촛불은 결코 사라지지 않았습니다.  
그 많은 사람들의 촛불이 조금만 더 용기를 낸다면,  
이 왜곡된 세상의 구조를 조금씩 바꾸어 갈 수 있을 것입니다.  

---


**Roh Moo-hyun**:  

> 제 장인은 좌익활동을 하다 돌아가셨습니다.  
그러나, 해방되는 해에 실명을 하셔서 앞을 보지 못했기 때문에  
무슨 일을 얼마나 했는지는 모르겠습니다.  
제가 결혼하기 훨씬 전에 돌아가셨는데,  
저는 이 사실을 알고 제 아내와 결혼했습니다.  
그리고, 아이들 잘 키우고, 지금까지 서로 사랑하면서 잘 살고 있습니다.  
뭐가 잘못됐습니까?  
이런 아내를 제가 버려야 합니까?  
그렇게 하면 대통령 자격이 있고, 이 아내를 그대로 사랑하면 대통령 자격이 없다는 것입니까?  
여러분, 이 자리에서 여러분들께서 심판해 주십시오.  
여러분이,  
여러분이 그런 아내를 가지고 있는 사람은 대통령 자격이 없다고 판단하신다면  
저 대통령 후보 그만두겠습니다.  
여러분이 하라고 하면 열심히 하겠습니다.  
(2002.4.6. 새천년민주당 제16대 대통령 선거 인천지역 국민경선 연설문 中)

**Han**:  
'과거'나 '출신'처럼 이상한 잣대로  
사람들을 '내 편'과 '니 편'으로 나누는 위험한 이분법 대신,  
존중과 이해를 통해  
화합을 만들어 가는 방법을 택하겠습니다.  
이것이야말로  
국가 지도자가 갖추어야 할 가장 중요한 자격이자,  
잊지 말아야 할 가장 중요한 임무라고 생각합니다.

"사랑"은 이념보다 더 깊고,  
"사람"은 과거의 낙인보다 더 높습니다.  
갈라치기로 사람을 나누는 세상이 아니라  
존중과 이해로 사람을 이어주는 세상을 향해  
한걸음 한걸음씩  
나아가겠습니다. 

---

**Roh Moo-hyun**:  
> 국민들과 눈높이를 맞추는 지도자가 되겠습니다.  
경호원 한두 명과 남대문 시장에, 자갈치 시장에, 동성로에, 금남로에, 은행동 거리에 모습을 나타내는 대통령,  
거기서 마주친 시민들과 소주 한 잔을 기울일 수 있는 대통령,  
그런 친구 같은 대통령이 되겠습니다.  
(2002.4.27. 새천년민주당 대통령 후보 수락 연설문 中)

**Han**:  
실천 없는 정의는 아무 쓸모 없습니다.  
국민들과 직접 함께 숨 쉬고, 함께 웃고, 함께 슬퍼보지 않는다면,  
"나도 너를 이해한다"는 말을 할 수 있는 자격조차 없을 것입니다. 

*"모두가 존엄을 지키며 살아가는 세상",*  
*"양심이 고개를 들고, 모두가 손 잡은 세상"...*  
*"정의가 무너지지 않는 세상",*  
*저도 끝까지 그런 세상을 위해 작은 힘을 보태겠습니다.*

*감사합니다,*  
