project:
  type: website
  output-dir: ../docs/book-gitsam-han

website:
  title: "[GitSAM](../index.html)"
  navbar:
    left:
      - text: "Papers"
        menu:
          - text: "Working"
            href: ../papers/index.html
          - text: "TBTF"
            href: ../paper-tbtf/index.html
      - text: "Books"
        menu:
          - text: "AI 기초 통계학"
            href: ../book-ai-stats/index.html
          - text: "AI 응용 선형대수학"
            href: ../book-ai-algebra/index.html
          - text: "AI 응용 미적분학"
            href: ../book-ai-calculus/index.html
          - text: "gitsam Han(恨)"
            href: index.html
      - text: "Apps"
        href: https://github.com/primenumbersam/
      - text: "스터디클럽"
        href: https://www.gitsam.com

    tools:
      - icon: shop
        href: https://laroe.co.kr/
      - icon: youtube
        href: https://www.youtube.com/@primenumbersam
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/primenumbersam/primenumbersam.github.io
          - text: Report a Bug
            href: mailto:primenumbersam@gmail.com

  sidebar:
    style: "floating"
    contents:
      - index.qmd
      - section: "애뜻함"
        contents:
        - 01-twain.qmd
        - 02-williams.qmd
        - 03-roh.qmd
        - 04-kim.qmd
        - 05-paramour.qmd
      - section: "매정함"
        contents:
        - c1-newton.qmd
        - c2-hobbes.qmd

author: gitSAM

date: "2025-05-15"

license: "CC BY-NC-SA 4.0"

format:
  html:
    theme: cosmo
    css: ../styles.css
    toc: false
    number-sections: false
    code-fold: true

execute:
  engine: jupyter
  freeze: auto

jupyter: python3