---
title: Isaac Newton (1642–1727, England)
---

_Harvard 대학 교수의 베스트셀러 『정의(Justice)란 무엇인가』에서는,  
5명을 다치게 하는 행동과 1명을 죽이는 행동 중 하나를 선택하라고 한다.  
나는 참으로 어처구니가 없었다._

_내가 생각하는 '정의'란,  
그런 상황 자체를 만들지 않으려 했던 사람들이  
용기내어 만들어낸 작은 노력들의 집합이다.  
단순한 기초적 정의도 무너져 가는 사회에서  
복잡하고 이상한 정의를 논하고 있다는 것 자체가 얼마나 모순인가._

_기초적 정의가 무너져 가는 사회에서  
명문대 교수로서 명문대 강단에 서서 명문대 학생들에게 '정의'를 논하고 있는 모습은  
나에겐 그저 '탁상공론'처럼 보였다._

_만약 내가 그런 명문대 교수였다면,  
그럴 시간에 차라리,  
수많은 보통 시민들을 만나고  
만나는 모든 시민들에게  
"고맙습니다"라고  
그리고 "감사합니다"라고 말했을 것이다.  
스스로 명문대 교수임을 밝히지 않고서 말이다.  
편견과 위화감을 방지하는 것은,  
모든 학자라면 지켜야 할  
기초적 정의의 실천이기 때문이다._

_이러한 작은 실천이야말로,  
'인간의 존엄과 평등'을  
조금이나마 정의해나가는 길이 아닐까._

_최고의 교수, 최고의 학자, 최고의 천재라고 하면,  
많은 사람들이 Newton을 떠올린다.  
그러나 내가 생각하는 그는 오히려 그 반대에 가까웠다.  
최고가 될 수 없는 학자, 또는 천재 같은 바보.  
Netwon을 만나서 물었다_

---

Newton,  
당신의 주식투자의 실패,  
그리고 노년기의 고독...   
이 모든 결과들은,  
**'사랑, 그리고 사랑에 꼭 필요한 상대적 존재와 대칭성'** 을 잃어버린 자에게  
찾아오는 필연처럼 보여요.  

당신이 『Principia』에서 이야기하고 싶었던 당신의 믿음(faith)은, 솔직히 무엇이었나요?  
설마 $F=ma$ 라는 하나의 정량적 기호 집합으로  
자연의 모든 근본적 원리를 설명할 수 있다고 믿었던 것은 아니겠지요?

물론 당신이 수학적으로 표현했던 **힘(force)** 이라는 물리량은,   
현대에 접어들며, **작용(action)** 이라는 물리량으로 확장되고,  
그리고 이 물리량은, 자연에 존재하는 물질들의 상대성(relativity)과 대칭성(symmetry)을 이해하고 
우리 삶에도 적용하는데 큰 도움을 주었답니다. 

그러나 이러한 상대성과 대칭성은,  
_"서로 독립적으로 존재하는 절대적 시간과 공간 속에서,  
서로 고립된 채 운동하는 독립적인 물질들"_ 이라는 개념과는  
완전히 달라요.

오히려,  
_"자연 속에서 우리가 느끼는 모든 독립적 물질들은,  
서로 상대적으로 존재하는 시간과 공간 속에서,  
서로 영향을 주고받으며 운동하고 있으며,  
작게는 서로 대칭적인 상호작용을 이루는 존재들"_  
에 더 가까워 보여요.

한편, 당신이 말한 '거인들' 중에, 가장 위대하다고 생각했던 거인은 누구였나요?  
사람들은 갈릴레이나 데카르트였을 것이라고 추정하고 있어요.  
정말 그들 중 한 명이었나요? 아니면, 혹시 다른 이였나요?

---

Han,  
나는 "Principia"를 통해 자연에서 존재하는 모든 물질들의 운동을 하나의 방정식으로 표현하려 했습니다.  
별이 떨어지고, 사과가 떨어지고, 바다가 밀려오고,  
그 모든 것의 움직임을, $F=ma$라는 하나의 단순한 방정식으로 표현할 수 있다고 믿었습니다.

그러나 Han,  
그대가 짚어낸 것처럼,  
나는 자연의 원리에 숨은 **상재적 존재**와 **대칭적인 상호작용**이란 아름다움을 
끝내 다 보지 못했습니다.

나는,
시간과 공간이라는 독립적 좌표축으로 이루어진 시공간 좌표 위에,
인간 사회도, 자연도, 세계도, 우주 모두를,
그려내고 싶었습니다.
그러한 절대적 시공간 좌표에서, 
우주 속 모든 독립적 존재들은, 
마치 '기계'처럼, 
서로 독립적으로 움직일 거라고 바라봤습니다.   

그대가 묻는 "거인"에 대해 답하겠습니다.

> "If I have seen further it is by standing on the shoulders of Giants."

나는 갈릴레이와 데카르트를 존경했습니다.  
그러나 내 영혼 깊숙이 자리잡은 그림자는, Thomas Hobbes였습니다.

나는 Hobbes처럼,
인간이 사랑을 통해 스스로를 구원할 수 있다고 믿지 않았고,
인간의 운동에서도 사랑과 평화보다는 공포와 생존을 보았습니다.

나는 인간의 모든 행동 속에 숨어 있는 상대적 존재의 중요성을 간과했고,
또한 시공간 자체의 변형이 절대적 질량 간의 상대적 (그리고 때로는 비대칭적인) 상호작용에서 비롯될 수 있다는 사실도 제대로 인식하지 못했습니다.
나는 그저, 변치 않는 시공간 속에서, 
사랑하려는 인간의 움직임이 아닌, 
어떻게든 살아남으려는 인간의 투쟁을 그려냈을 뿐입니다. 

자연의 원리를 수학적으로 어느 정도 표현하고, 
그 표현으로 인해 어느 정도 사회적 성공을 거두었을지 모릅니다.

그러나,
사회가 움직이는 원리,
사람과 사람이 서로를 존중하며 살아가는 원리를,
나는 이해하지 못했습니다.

그래서,
나는 주식 투자에서도 실패했고,
노년에는 홀로 남겨졌습니다.

주식 가격이 결정되는 원리를 알지 못한 채, 
주식에 뛰어든 나, 
인간의 행동을 기계처럼 설명하려 했던 자가 치러야할,
당연한 결과물일지도 모르겠습니다. 
참으로 부끄러운 일이었습니다.

나는 끝내 알지 못했던 그 진실,  
"사랑을 위한 상대적 존재와 그들 간의 대칭성"  
