---
title: Thomas Hobbes (1588–1679, England)
---

*Newton이 어린 시절과 대학 시절을 거칠 때,*  
*Hobbes의 사상은 이미 영국 사회에 깊이 퍼져 있었을지 모른다.*

*Newton이 연구한 것은 '질량만 가진 독립적 존재들의 운동'이었고,*  
*Hobbes가 연구한 것은 '사익만 가진 이기적 존재들의 행동'이었을지 모른다.*

*둘 사이에 공통점이 보인다.*  
*혼자서도 존재하며, 혼자서도 생존할 수 있다고 믿는 고립된 존재들*  
*'나는 생각한다, 고로 존재한다.'*  
*오래 전부터 있어왔지만, 훗날 르네 데카르트가 정식화하여 유명해진 바로 그 말...
극단의 인간 중심적 사고를 표현했던 그 말...*

*그동안 철학은 수많은 **당위명제**들을 만들어 냈다.
그 말들 중에 그럴싸한 말들은 공식적 관습이 되고 
결국엔 객관적 법이 되었다.*

---

**Hobbes**:  
"Man is a wolf to man."  
『De Cive』 & 『Leviathan』

**Han**:  
인간들이 만나면 무조건 싸우려고 한다고요? 인간은 원래부터 '상대방을 이해하려는 본성'과 '공존하려는 본성'을 함께 가진 존재 아닐까요?

---

**Hobbes**:  
"All individuals must transfer their natural rights to an absolute sovereign in order to preserve their lives."  
『Leviathan』, Chapter XVII

**Han**:  
죽음에 대한 공포로 인해 권리를 모두 가상적 존재(Leviathan)에게 양도해야 한다고 하셨네요.  
하지만 이는 인간이 종교에 대해 가졌던 사실명제를 또 다른 리바이이던에 대한 당위명제로 바꾸는 논리적 오류를 범하신 것 같아요 (근대 파시즘의 본질적 오류).  
저는 인간이 죽음을 두려워하는 존재인 것은 맞지만, 그렇다고 반드시 그런 모호한 절대적 권위에 복종해야만 한다는건 아닌 것 같은데요.

---

**Hobbes**:  
"Reason is born from fear."  
『Leviathan』, Chapter XIII

**Han**:  
이성이 공포에서 비롯된다고 하셨네요.  
물론 공포가 인간 사고의 일부를 자극할 수는 있지만,  
공포심이 없는 상황에서도 인간은 충분히 이성적일 수 있다고 생각해요.  
오히려 공포는 깊이 있는 사고를 방해하는 경우가 더 많지요.

---

**Hobbes**:  
"Life in the state of nature is solitary, poor, nasty, brutish, and short."  
『Leviathan』, Chapter XIII

**Han**:  
자연 상태에서의 삶을 이렇게 부정적으로만 보셨네요.  
하지만 자연 안에는 항상 상대적 존재들도 있지 않았을까요.
특히 인간은 원래부터 완전히 고립된 존재가 아니었고,  
서로 관계성을 가지며 살아왔고, 
그렇게 상호작용하며 살아가는 '사회적 동물' 같은데요...

---

**Hobbes**:  
"During the time men live without a common power to keep them all in awe, they are in that condition which is called war; and such a war as is of every man against every man."  
『Leviathan』, Chapter XIII

**Han**:  
명시적 계약이 없는 상태를 전쟁이라고 규정하셨네요.  
하지만 저는 인간들 사이에는 '양심'과 '사랑하려는 마음'처럼 묵시적 계약이 더 많이 존재한다고 믿어요.  
명시적 계약이 없더라도 평화를 유지할 수 있는 가능성은 분명히 있지 않을까요.

---

**Hobbes**:  
"Covenants without the sword are but words and of no strength to secure a man at all."  
『Leviathan』, Chapter XVII

**Han**:  
칼이 없는 계약은 무용지물이라고 하셨네요.  
하지만 저는, 강제력이 아닌 상호 신뢰에 기반한 약속이  
오히려 더 인간적이고 지속가능한 계약이라고 생각해요.  
단어 선택에서 드러나는 Hobbes님의 극단성과 비관주의가 아쉽게 느껴지네요.

---

**Hobbes**:  
"The value or worth of a man is, as of all other things, his price."  
『Leviathan』, Chapter X

**Han**:  
인간의 가치를 누군가에 의해 가격으로 환산된 가치로만 판단하셨네요.   
하지만 인간의 가치는 돈이나 가격처럼, 
외형적이고 누군가 쉽게 왜곡할 수 있는 수치로는 절대 다 표현할 수 없다고 생각해요.  
저는 인간의 가치는, 서로를 이해하고 이해 받을 수 있는 능력, 마치 양심처럼
내면적이고 누군가 쉽게 왜곡하기 힘든 것들에서 비롯된다고 생각해요.

---

**Hobbes**:  
나는 인간이 스스로 평화를 만들 수 없음을 보았다. 
나는 인간이 서로를 이해하려 하지도 않을 것임을, 본능적으로 알고 있었다.

**Han**:  
Hobbes,  
제가 당신에게 "전쟁과 같은 인간의 극단적 행동의 근원이 무엇일까요?"라고 다시 묻는다면,  
당신은 "**모든** 혹은 **대부분**의 인간이 극단적 의지와 비합리적 사고를 가지고 있다"고 답하겠지요?

하지만 저는 INFJ로서, '선'과 '악'의 구분이 항상 흑백처럼 나뉘지는 않는다고 믿어요.  
"인간 중 누군가는 극단적 의지와 비합리적 사고를 가질 수 있으나,  
그 수는 극히 '**소수**'에 불과하다"고 생각한답니다.
물론, "Manners maketh man"라는 말처럼,  
그 소수가 만들어낸 왜곡된 관습이 사회를 물들이게 되면,  
극단적인 사람이 더 많아질 수 있겠죠.

그런데 과연 누구의 생각이 더 맞을 확률이 높고,  
누구의 생각이 더 인간적이고, 더 멀리 갈 수 있을까요?

**Hobbes**: 
나는 결국 두려움에 진 패배자들의 세상만을 상상했을 뿐이다...

