project:
  type: website
  output-dir: ../docs/book-ai-stats

website:
  favicon: ../assets/favicon.png
  navbar:
    logo: ../assets/logo-nav.png
    logo-href: ../index.html
    search: true
    left:
      - text: "Apps"
        href: https://github.com/primenumbersam/
      - text: "Books"
        menu:
          - text: "AI 기초 수학"
            href: ../book-ai-math/index.html
          - text: "AI 기초 통계학"
            href: index.html
          - text: "AI 응용 선형대수학"
            href: ../book-ai-algebra/index.html
          - text: "AI 응용 미적분학"
            href: ../book-ai-calculus/index.html
      - text: "Papers"
        menu:
          - text: "Working"
            href: ../papers/index.html
          - text: "Thesis"
            href: ../paper-tbtf/index.html
    tools:
      - icon: github
        href: https://github.com/primenumbersam/primenumbersam.github.io

  page-footer:
    border: false
    background: light
    left: "© 2025 · GITSAM · All rights reserved"
    right:
      - icon: youtube
        href: https://www.youtube.com/@primenumbersam
      - icon: instagram
        href: https://instagram.com/primenumbersam
      - icon: shop
        href: https://laroe.co.kr/

  sidebar:
    style: "floating"
    contents:
      - index.qmd
      - section: "통계 데이터 (Statistical Data)"
        contents:
        - 1-1.qmd
        - 1-2.qmd
        - 1-3.qmd
        - 1-4.qmd
      - section: "데이터 탐색 (Exploration)"
        contents:
        - 2-1.qmd
        - 2-2.qmd
      - section: "데이터와 가설의 연결고리 (Probability)"
        contents:
        - 3-1.qmd
        - 3-2.qmd
        - 3-3.qmd
        - 3-4.qmd
      - section: "데이터 활용 (Exploitation)"
        contents:
        - 4-1.qmd
        - 4-2.qmd
        - 4-3.qmd
        - 4-4.qmd
        - 4-5.qmd
      - section: "모형계수 추정법 (Estimation)"
        contents:
        - 5-1.qmd
        - 5-2.qmd
        - 5-3.qmd
      - section: "가설 점정 (Hypothesis Test)"
        contents:
        - 6-1.qmd
        - 6-2.qmd
        - 6-3.qmd
        - 6-4.qmd

license: "CC BY-NC-SA 4.0"

format:
  html:
    include-in-header: "../analytics.html"
    theme:
      light: cosmo
      dark: cyborg
    appearance: toogle
    toc: true
    number-sections: true
    code-fold: true

execute:
  engine: jupyter
  freeze: auto

jupyter: python3