project:
  type: website
  output-dir: ../docs/papers

website:
  favicon: ../assets/favicon.png
  navbar:
    logo: ../assets/logo-nav.png
    logo-href: ../index.html
    search: true
    left:
      - text: "Apps"
        href: https://github.com/primenumbersam/
      - text: "Books"
        menu:
          - text: "AI 기초 수학"
            href: ../book-ai-math/index.html
          - text: "AI 기초 통계학"
            href: ../book-ai-stats/index.html
          - text: "AI 응용 선형대수학"
            href: ../book-ai-algebra/index.html
          - text: "AI 응용 미적분학"
            href: ../book-ai-calculus/index.html
      - text: "Papers"
        menu:
          - text: "Working"
            href: index.html
          - text: "Thesis"
            href: ../paper-tbtf/index.html
    tools:
      - icon: github
        href: https://github.com/primenumbersam/primenumbersam.github.io

  page-footer:
    border: false
    background: light
    left: "© 2025 · GITSAM · All rights reserved"
    right:
      - icon: youtube
        href: https://www.youtube.com/@primenumbersam
      - icon: instagram
        href: https://instagram.com/primenumbersam
      - icon: shop
        href: https://laroe.co.kr/

  sidebar:
    style: floating
    contents:
      - index.qmd
      - section: "경제"
        contents:
        - gitsam_reading.qmd
        - indicator_growth.qmd
        - labor_decoupling.qmd
        - regressions.qmd
        - pareto_index.qmd
        - gilded_age.qmd
        - modern_matthew.qmd        
        - dichotomy.qmd
        - pricing_equal.qmd
        - corner_solution.qmd
        - market_conditions.qmd
        - market_incomplete.qmd
        - structure_cointegration.qmd
        - structure_tfp.qmd
      - section: "금융"
        contents: 
        - yield_curve.qmd
        - correlation_crypto.qmd
        - finance_asset_puzzle.qmd
        - finance_linear.qmd
        - finance_existence.qmd
        - capm.qmd
        - capm_industry.qmd
      - section: "돈의 동역학"
        contents:
        - d_overview.qmd
        - d_1_critique.qmd
        - d_2_elementary.qmd
        - d_3_model.qmd
        - d_4_ethics.qmd

format:
  html:
    include-in-header: "../analytics.html"
    theme:
      light: cosmo
      dark: cyborg
    appearance: toogle
    toc: true
    number-sections: true
    code-fold: true

execute:
  engine: jupyter
  freeze: auto

jupyter: python3