project:
  type: website
  output-dir: ../docs/papers

website:
  title: "[GitSAM](../index.html)"
  navbar:
    left:
      - text: "Papers"
        menu:
          - text: "Working"
            href: index.html
          - text: "TBTF"
            href: ../paper-tbtf/index.html
      - text: "Books"
        menu:
          - text: "gitsam 기초통계학"
            href: ../book-gitsam-stats/index.html
          - text: "AI 응용 선형대수학"
            href: https://primenumbersam.github.io/
      - text: "Apps"
        href: https://github.com/primenumbersam/
      - text: "스터디클럽"
        href: https://www.gitsam.com

    tools:
      - icon: shop
        href: https://laroe.co.kr/
      - icon: youtube
        href: https://www.youtube.com/@primenumbersam
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/primenumbersam/primenumbersam.github.io
          - text: Report a Bug
            href: mailto:primenumbersam@gmail.com

  sidebar:
    style: floating
    contents:
      - index.qmd
      - section: "경제"
        contents:
        - gitsam_reading.qmd
        - indicator_growth.qmd
        - labor_decoupling.qmd
        - regressions.qmd
        - pareto_index.qmd
        - gilded_age.qmd
        - modern_matthew.qmd        
        - dichotomy.qmd
        - pricing_equal.qmd
        - corner_solution.qmd
        - market_conditions.qmd
        - market_incomplete.qmd
        - structure_cointegration.qmd
        - structure_tfp.qmd
      - section: "금융"
        contents: 
        - yield_curve.qmd
        - correlation_crypto.qmd
        - finance_asset_puzzle.qmd
        - finance_linear.qmd
        - finance_existence.qmd
        - capm.qmd
        - capm_industry.qmd
      - section: "돈의 동역학"
        contents:
        - d_overview.qmd
        - d_1_critique.qmd
        - d_2_elementary.qmd
        - d_3_model.qmd
        - d_4_ethics.qmd

author: gitSAM

format:
  html:
    theme: cosmo
    css: ../styles.css
    toc: true
    number-sections: false
    code-fold: true

execute:
  engine: jupyter
  freeze: auto

jupyter: python3