{
  "hash": "224c62f0eeede162c0f2b235390221b7",
  "result": {
    "engine": "jupyter",
    "markdown": "---\ntitle: 07 Robustness\nsubtitle: Is TBTF Sadly Optimal by Design?\nexecute:\n  enabled: true\n---\n\n\n\n\nWhile the previous section focused on the performance outcomes of the TBTF strategy, this section evaluates the **stability of those outcomes** under variation in core implementation parameters. We test whether the superior performance persists under changes in portfolio size, rebalancing frequency, weighting schemes, and look-back windows.\n\nRather than relying on a single optimized configuration, the TBTF strategy demonstrates **structural robustness across plausible alternatives**. This not only reinforces the credibility of the results, but also supports the **practical adaptability** of the approach for different institutional contexts.\n\nAll robustness tests are performed on the post-2010 period, with out-of-sample investment beginning on **2010-01-01**. The portfolio is trained using a 48-month rolling window (`in_sample=48M`) and evaluated through 2023-12-31.\n\n::: {#d85cf2d3 .cell execution_count=1}\n``` {.python .cell-code}\nimport pandas as pd\nimport sqlite3\ncons = sqlite3.connect(database=\"../../tbtf.sqlite\")\n\ncrsp = pd.read_sql_query(\n  sql=\"SELECT * FROM crsp\",\n  con=cons,\n  parse_dates={\"date\"}\n)\n```\n:::\n\n\n::: {#22db31ef .cell execution_count=2}\n``` {.python .cell-code}\n# Out-of-sample Investment\nimport sys\nimport os\n# 현재 경로 기준으로 상위 디렉토리로 경로 추가\nsys.path.append(os.path.abspath('../..'))\n\nimport tbtf\n\n\n# robust check 대상 파라미터 설정\ntop_ns = [5, 7, 10, 15, 20]\nrebalance_freqs = ['3M', '6M', '12M']\nweighting_methods = ['exponential', 'quadratic', 'value', 'equal']\n\n# 기본 설정 정리\nin_end = '2009-12-31'         # in-sample 끝\nout_end = '2023-12-31'        # out-of-sample 끝\nin_sample_months = 48         # in-sample 기간 (예: 4년)\neta = 3                       # CRRA 계수\np = 0.01                      # Omega Ratio threshold\nstate = 10\n\n\nfrom joblib import Parallel, delayed\n\ndef run_single_backtest(method, n, freq):\n    result = tbtf.backtest_pipeline(\n        crsp=crsp,\n        in_end=in_end,\n        out_end=out_end,\n        in_sample_months=in_sample_months,\n        rebalance_freq=freq,\n        weighting_method=method,\n        top_n=n,\n        state=state,\n        eta=eta,\n        p=p\n    )\n    perf = result['performance']\n    perf.update({'n': n, 'rebalance_freq': freq, 'weighting_method': method})\n\n    turnover_df = result['turnover']\n    total_turnover = turnover_df.iloc[:-1]['turnover'].sum() if len(turnover_df) > 1 else np.nan\n\n    return perf, {'n': n, 'rebalance_freq': freq, 'weighting_method': method, 'total_turnover': total_turnover}\n```\n:::\n\n\n::: {#78e5c5ce .cell execution_count=3}\n``` {.python .cell-code}\nfrom itertools import product\n\nparam_grid = list(product(weighting_methods, top_ns, rebalance_freqs))\n\n# 병렬 실행\nresults = Parallel(n_jobs=-1)(delayed(run_single_backtest)(method, n, freq) for method, n, freq in param_grid)\n\n# Robustness check 결과 DataFrame 생성\nperformance_df = pd.DataFrame([r[0] for r in results])\nturnover_summary_df = pd.DataFrame([r[1] for r in results])\n```\n:::\n\n\n## By Weighting Method\nWe begin by comparing the four weighting schemes: exponential, quadratic, value-weighted, and equal-weighted portfolios. The results show that TBTF's **convex weighting** yields consistently superior risk-adjusted performance, particularly in terms of expected CRRA utility and downside-sensitive metrics like the Omega ratio. We set the CRRA parmater $\\eta = 3$ to reflect moderate risk aversion and $p = 0.01$ to evaluate downside risk via the Omega Ratio at the minimum 1% monthly threshold.\n\n::: {#1dca9a36 .cell tbl-cap='Good Performance Metrics by Weighting Method' execution_count=4}\n``` {.python .cell-code}\nmetrics = ['Expected CRRA', 'Annualized Return', 'Sharpe Ratio', 'Sortino Ratio', 'Calmar Ratio', 'Omega Ratio', 'Max Drawdown']\nperformance_df.groupby('weighting_method')[metrics].median().round(3).sort_values(by='Expected CRRA', ascending=False)\n```\n\n::: {.cell-output .cell-output-display execution_count=4}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Expected CRRA</th>\n      <th>Annualized Return</th>\n      <th>Sharpe Ratio</th>\n      <th>Sortino Ratio</th>\n      <th>Calmar Ratio</th>\n      <th>Omega Ratio</th>\n      <th>Max Drawdown</th>\n    </tr>\n    <tr>\n      <th>weighting_method</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>exponential</th>\n      <td>0.020</td>\n      <td>0.051</td>\n      <td>0.766</td>\n      <td>1.444</td>\n      <td>0.430</td>\n      <td>2.155</td>\n      <td>-0.134</td>\n    </tr>\n    <tr>\n      <th>quadratic</th>\n      <td>0.020</td>\n      <td>0.052</td>\n      <td>0.779</td>\n      <td>1.443</td>\n      <td>0.433</td>\n      <td>2.182</td>\n      <td>-0.132</td>\n    </tr>\n    <tr>\n      <th>value</th>\n      <td>0.020</td>\n      <td>0.050</td>\n      <td>0.770</td>\n      <td>1.454</td>\n      <td>0.435</td>\n      <td>2.147</td>\n      <td>-0.134</td>\n    </tr>\n    <tr>\n      <th>equal</th>\n      <td>0.018</td>\n      <td>0.045</td>\n      <td>0.727</td>\n      <td>1.326</td>\n      <td>0.382</td>\n      <td>1.967</td>\n      <td>-0.135</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#53bc3fd7 .cell tbl-cap='Bad Performance Metric by Weighting Method' execution_count=5}\n``` {.python .cell-code}\nmetrics = ['Annualized Volatility', 'Pearson Skewness', 'Excess Kurtosis']\nperformance_df.groupby('weighting_method')[metrics].median().round(3).sort_values(by='Annualized Volatility', ascending=True)\n```\n\n::: {.cell-output .cell-output-display execution_count=5}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th></th>\n      <th>Annualized Volatility</th>\n      <th>Pearson Skewness</th>\n      <th>Excess Kurtosis</th>\n    </tr>\n    <tr>\n      <th>weighting_method</th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>equal</th>\n      <td>0.064</td>\n      <td>-0.341</td>\n      <td>0.307</td>\n    </tr>\n    <tr>\n      <th>exponential</th>\n      <td>0.068</td>\n      <td>-0.240</td>\n      <td>0.752</td>\n    </tr>\n    <tr>\n      <th>value</th>\n      <td>0.068</td>\n      <td>-0.144</td>\n      <td>0.524</td>\n    </tr>\n    <tr>\n      <th>quadratic</th>\n      <td>0.069</td>\n      <td>-0.214</td>\n      <td>0.791</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#c118f232 .cell execution_count=6}\n``` {.python .cell-code}\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\n#sns.violinplot(data=performance_df, x='weighting_method', y='Annualized Volatility')\nsns.boxplot(data=performance_df, x='weighting_method', y='Sharpe Ratio')\nplt.title(\"Metric Distribution by Weighting Method\")\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](4_7_robustness_files/figure-html/cell-7-output-1.png){}\n:::\n:::\n\n\nThese results suggest that nonlinear weighting schemes are critical to capturing the TBTF premium. Among them, the quadratic method slightly outperforms exponential weighting across most performance metrics, including the highest **median** Omega ratio (2.182) and lowest median max drawdown (−13.2%). Given that both exponential and quadratic weighting schemes yield nearly identical results under the median of CRRA-based metrics, the exponential weighting—though rooted in CRRA-type concentration—offers no clear advantage over the quadratic scheme, which continues to strike a robust balance between concentration and diversification.\n\n## By Asset Selection Size (`top_n`)\n\nNext, we vary the number of selected stocks, ranging from 5 to 20. The results clearly show that performance declines as top_n increases, confirming that capital concentration—not mere size exposure—is the key driver.\n\n::: {#73674bbe .cell tbl-cap='Sharpe Ratio by Weighting Method and Top-n' execution_count=7}\n``` {.python .cell-code}\nperformance_df.pivot_table(\n    values='Sharpe Ratio',\n    index='weighting_method',\n    columns='n',\n    aggfunc='mean'\n)\n```\n\n::: {.cell-output .cell-output-display execution_count=7}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>n</th>\n      <th>5</th>\n      <th>7</th>\n      <th>10</th>\n      <th>15</th>\n      <th>20</th>\n    </tr>\n    <tr>\n      <th>weighting_method</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>equal</th>\n      <td>0.608791</td>\n      <td>0.627588</td>\n      <td>0.605765</td>\n      <td>0.584674</td>\n      <td>0.585974</td>\n    </tr>\n    <tr>\n      <th>exponential</th>\n      <td>0.636665</td>\n      <td>0.648066</td>\n      <td>0.622787</td>\n      <td>0.604382</td>\n      <td>0.602568</td>\n    </tr>\n    <tr>\n      <th>quadratic</th>\n      <td>0.612236</td>\n      <td>0.642290</td>\n      <td>0.630014</td>\n      <td>0.610713</td>\n      <td>0.597321</td>\n    </tr>\n    <tr>\n      <th>value</th>\n      <td>0.616514</td>\n      <td>0.633672</td>\n      <td>0.615023</td>\n      <td>0.608970</td>\n      <td>0.605151</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\n::: {#6fdb5a7a .cell tbl-cap='Expected CRRA Utility across Weighting Methods and Top-n' execution_count=8}\n``` {.python .cell-code}\nperformance_df.pivot_table(\n    values='Expected CRRA',\n    index='weighting_method',\n    columns='n'\n).round(4)\n```\n\n::: {.cell-output .cell-output-display execution_count=8}\n```{=html}\n<div>\n<style scoped>\n    .dataframe tbody tr th:only-of-type {\n        vertical-align: middle;\n    }\n\n    .dataframe tbody tr th {\n        vertical-align: top;\n    }\n\n    .dataframe thead th {\n        text-align: right;\n    }\n</style>\n<table border=\"1\" class=\"dataframe\">\n  <thead>\n    <tr style=\"text-align: right;\">\n      <th>n</th>\n      <th>5</th>\n      <th>7</th>\n      <th>10</th>\n      <th>15</th>\n      <th>20</th>\n    </tr>\n    <tr>\n      <th>weighting_method</th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n      <th></th>\n    </tr>\n  </thead>\n  <tbody>\n    <tr>\n      <th>equal</th>\n      <td>0.0168</td>\n      <td>0.0167</td>\n      <td>0.0141</td>\n      <td>0.0119</td>\n      <td>0.0110</td>\n    </tr>\n    <tr>\n      <th>exponential</th>\n      <td>0.0175</td>\n      <td>0.0174</td>\n      <td>0.0154</td>\n      <td>0.0135</td>\n      <td>0.0125</td>\n    </tr>\n    <tr>\n      <th>quadratic</th>\n      <td>0.0167</td>\n      <td>0.0172</td>\n      <td>0.0156</td>\n      <td>0.0138</td>\n      <td>0.0127</td>\n    </tr>\n    <tr>\n      <th>value</th>\n      <td>0.0166</td>\n      <td>0.0168</td>\n      <td>0.0151</td>\n      <td>0.0139</td>\n      <td>0.0130</td>\n    </tr>\n  </tbody>\n</table>\n</div>\n```\n:::\n:::\n\n\nVarying the number of selected stocks from 5 to 20 reveals a consistent trend: risk-adjusted performance tends to decline once the portfolio exceeds $n=7$.\n\nThis pattern implies that the TBTF premium is not a gradual function of portfolio size, but instead concentrated at the extreme upper tail of the capital distribution. The declining marginal benefit of including additional assets reflects the structural nature of capital lock-in—only the very largest firms systematically attract persistent investor flows, benefit from narrative insulation, and receive reinforcement through index inclusion.\n\nNotably, traditional weighting schemes (Value or Equal) consistently underperform compared to TBTF-based weightings (Exponential or Quadratic) when $n < 15$, highlighting the importance of embedding size asymmetry in portfolio construction.\n\n\n## Rebalancing Frequency and Turnover Tradeoff\n\n::: {#2c5ad00e .cell execution_count=9}\n``` {.python .cell-code}\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\n# 원하는 순서로 정렬\nrebalance_order = ['3M', '6M', '12M']\nn_order = sorted(performance_df['n'].unique(), reverse=True)  # n=5,7,10,15,20 등 오름차순\n\n# Pivot and reorder\npivot_sharpe = (\n    performance_df.pivot_table(\n        values='Sharpe Ratio',\n        index='n',\n        columns='rebalance_freq'\n    )\n    .loc[n_order, rebalance_order]  # y축 (n), x축 (rebalance_freq) 순서 정렬\n    .round(2)\n)\n\n# Pivot을 위한 사용자 정의 함수\ndef best_weighting_by_sharpe(df):\n    idx = df.groupby(['n', 'rebalance_freq'])['Sharpe Ratio'].idxmax()\n    best_df = df.loc[idx, ['n', 'rebalance_freq', 'weighting_method']]\n    pivot = best_df.pivot(index='n', columns='rebalance_freq', values='weighting_method')\n\n    # 시각화-friendly 정렬\n    pivot = pivot.loc[sorted(pivot.index, reverse=True), ['3M', '6M', '12M']]\n    return pivot\n\nbest_weighting_pivot = best_weighting_by_sharpe(performance_df)\n\n# 결과 출력\n# display(best_weighting_pivot)\n\nplt.figure(figsize=(8, 5))\n# sns.heatmap(pivot_sharpe, annot=True, cmap=\"YlGnBu\", cbar_kws={'label': 'Sharpe Ratio'})\nsns.heatmap(\n    pivot_sharpe,  # 기존 numeric table\n    annot=best_weighting_pivot.values,  # 텍스트는 scheme 이름으로\n    fmt='',  # 숫자 포맷 아님\n    cmap=\"YlGnBu\",\n    cbar_kws={'label': 'Sharpe Ratio'}\n)\nplt.title(\"Best Weighting Method by Sharpe Ratio\")\nplt.xlabel(\"Rebalancing Frequency\")\nplt.ylabel(\"Number of Selected Assets (n)\")\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Sharpe Ratio Heatmap (Top-n vs Rebalancing Frequency)](4_7_robustness_files/figure-html/cell-10-output-1.png){}\n:::\n:::\n\n\nWe next examine the impact of rebalancing frequency—specifically, quarterly (`3M`), semiannual (`6M`), and annual (`12M`)—on risk-adjusted performance and underlying portfolio structure. As shown in the heatmap above, quarterly rebalancing tends to produce higher Sharpe ratios across most configurations. However, this benefit comes at the cost of substantially higher turnover. We find that shorter rebalancing intervals better preserve the structural core of TBTF portfolios. Quarterly updates maintain capital concentration and produce stable weight dynamics, while longer horizons may induce drift and dilute structural persistence—especially at larger `n`.\n\n::: {#280c5eb2 .cell execution_count=10}\n``` {.python .cell-code}\nimport seaborn as sns\nimport matplotlib.pyplot as plt\n\nsns.boxplot(data=turnover_summary_df, x='weighting_method', y='total_turnover', hue='rebalance_freq')\nplt.title(\"Turnover Distribution by Weighting and Frequency\")\nplt.grid(True)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Total Turnover across Parameters](4_7_robustness_files/figure-html/cell-11-output-1.png){}\n:::\n:::\n\n\n::: {#f8b6ba93 .cell execution_count=11}\n``` {.python .cell-code}\nsns.boxplot(\n    data=turnover_summary_df,\n    x='weighting_method',\n    y='total_turnover',\n    hue='n'  # Top-n 구성 자산 수\n)\nplt.title(\"Turnover Distribution by Weighting and Top-n\")\nplt.grid(True)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![Total Turnover across Parameters](4_7_robustness_files/figure-html/cell-12-output-1.png){}\n:::\n:::\n\n\nTo assess the practical implementability of the TBTF strategy, we examine the total turnover across different weighting schemes and rebalancing frequencies. As illustrated in the boxplot above, turnover levels vary meaningfully by configuration, offering insights into the structural dynamics of each method.\n\nTBTF weighting methods—particularly under less frequent rebalancing (e.g., quarterly or semiannual)—consistently exhibit lower interquartile ranges of turnover, indicating a high degree of structural stability in portfolio composition. In contrast, equal weighting yields the widest dispersion, reflecting more volatile asset entry and reallocation patterns due to its lack of embedded capital sensitivity.\n\nAcross all weighting methods, turnover responds strongly to changes in rebalancing frequency. Reducing the frequency from quarterly to semiannual, and from semiannual to annual, results in approximately a twofold decline in average turnover at each step. This regularity highlights a core tradeoff: finer rebalancing intervals enable more timely tracking of short-term shifts but also introduce greater portfolio churn.\n\nA noteworthy exception emerges within the TBTF schemes: quadratic weighting produces higher turnover when moving from semiannual to annual rebalancing—a reversal of the pattern observed in all other methods. This suggests that the quadratic weighting’s greater sensitivity to initial rank–capital structure may amplify reallocations over longer horizons, especially if the top decile membership becomes more volatile at lower rebalancing frequencies.\n\nTaken together, these findings suggest that TBTF-based weighting offers the most stable tradeoff between capital concentration and transaction frictions. In particular, rebalancing at a semiannual or quarterly frequency appears to strike a practical balance, preserving capital lock-in dynamics while keeping turnover at manageable levels.\n\nWe further analyze turnover as a function of the number of selected stocks, visualized in the \"Turnover Distribution by Weighting and Top-n\" plot. Here, TBTF, value-weighted, and equal-weighted portfolios all exhibit their most stable and lowest turnover levels at $n = 10$ and $n = 20$. Interestingly, turnover does not decline monotonically as the number of holdings increases. For example, moving from $n = 10$ to $n = 15$ slightly increases total turnover before falling again at $n = 20$. This non-monotonicity suggests that portfolio stability is not simply a function of size, but also of how concentration thresholds interact with the rank dynamics of capital allocation.\n\n::: {#d4a934e7 .cell execution_count=12}\n``` {.python .cell-code}\n# Merge performance & turnover\nmerged_df = pd.merge(performance_df, turnover_summary_df,\n                     on=['n', 'rebalance_freq', 'weighting_method'])\n\n#| fig-cap: \"Performance Metric vs. Turnover Tradeoff\"\nsns.scatterplot(data=merged_df,\n                x='total_turnover',\n                y='Expected CRRA',\n                hue='weighting_method',\n                style='rebalance_freq')\nplt.title(\"Performance vs. Turnover Tradeoff\")\nplt.grid(True)\nplt.tight_layout()\nplt.show()\n```\n\n::: {.cell-output .cell-output-display}\n![](4_7_robustness_files/figure-html/cell-13-output-1.png){}\n:::\n:::\n\n\nFinally, we visualize the performance-turnover tradeoff, showing how each strategy balances return and implementation frictions:\n\nThe figure above visualizes the tradeoff between expected CRRA utility and total turnover across all strategy configurations. Each point represents a unique combination of `n`, `rebalance_freq`, and `weighting_method`.\n\nThe resulting plot reveals distinct horizontal clusters by rebalancing frequency, especially under the post-2010 regime. This banding effect is most likely driven by regime-specific shocks—particularly the COVID-19 crash, which had sharply divergent effects depending on the timing of portfolio adjustment.\n\nTo further analyze this, we compute the expected CRRA per unit of turnover (i.e., $\\frac{\\text{Expected CRRA}}{\\text{Total Turnover}}$) across time subperiods. During non-crisis periods, 6M and 12M configurations yield comparable ratios, with 3M performing slightly lower due to higher turnover. However, during the COVID-19 period, the 6M rebalancing interval dominates, suggesting that it hit a timing sweet spot—being responsive enough to adapt, but not overly reactive like 3M or sluggish like 12M.\n\nThese findings underscore the importance of considering macro-structural shocks in assessing turnover efficiency. While quarterly rebalancing ensures persistence and structural alignment, semiannual updates may offer better resilience under nonlinear market stress, at least in crisis regimes.\n\n\n## Summary of Robustness\n\nAcross a broad set of configurations, the TBTF strategy exhibits strong structural robustness. Its performance remains resilient to changes in portfolio size, weighting method, and rebalancing frequency, indicating that its effectiveness does not hinge on a narrow set of parameter choices.\n\nThe consistent superiority of nonlinear weighting schemes—particularly exponential and quadratic—underscores that the TBTF effect stems not merely from large-cap exposure, but from deliberate capital concentration. At the same time, the diminishing performance observed as the number of included assets increases confirms that the strategy draws its strength from a small group of dominant firms at the top of the capital hierarchy.\n\nIn implementation terms, both quarterly and semiannual rebalancing strike workable tradeoffs. Quarterly updates better preserve structural lock-in, while semiannual schedules offer greater resilience during regime shocks, such as the COVID-19 episode. Turnover remains moderate in both cases, especially under quadratic weighting, which achieves stability without compromising returns.\n\nTaken together, the evidence suggests that TBTF is neither an artifact of tuning nor a fragile anomaly. Rather, it is a reflection of deeper structural features—platform dominance, passive reinforcement, and institutional persistence—that increasingly govern capital allocation in modern markets.\n\n",
    "supporting": [
      "4_7_robustness_files"
    ],
    "filters": [],
    "includes": {
      "include-in-header": [
        "<script src=\"https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js\" integrity=\"sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==\" crossorigin=\"anonymous\"></script>\n<script src=\"https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js\" integrity=\"sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==\" crossorigin=\"anonymous\" data-relocate-top=\"true\"></script>\n<script type=\"application/javascript\">define('jquery', [],function() {return window.jQuery;})</script>\n"
      ]
    }
  }
}