project:
  type: website
  output-dir: ../docs/thesis

website:
  title: "[GitSAM](../index.html)"
  navbar:
    left:
      - text: 교육
        href: ../guides/index.html
      - text: 연구
        href: ../projects/index.html
      - text: TBTF
        href: index.qmd
        
    tools:
      - icon: house
        href: https://www.gitsam.com
      - icon: youtube
        href: https://www.youtube.com/@primenumbersam
      - icon: github
        menu:
          - text: Source Code
            href: https://github.com/primenumbersam/primenumbersam.github.io
          - text: Report a Bug
            href: mailto:primenumbersam@gmail.com

  sidebar:
    style: floating
    contents:
      - index.qmd
      - 1_intro.qmd
      - 2_lit_review.qmd
      - section: "History"
        contents:
        - 3_1_history.qmd
        - 3_2_history_nyse.qmd
      - section: "Model"
        contents:
        - 4_1_overview.qmd
        - 4_2_data.qmd
        - 4_3_ff_compare.qmd
        - 4_4_structure.qmd
        - 4_5_strategy.qmd
        - 4_6_performance.qmd
        - 4_7_robustness.qmd
        - 4_8_implementation.qmd
      - 05_conclusion.qmd

author: gitSAM
date: '2025-03-31'
bibliography: references.bib

format:
  html:
    theme: cosmo
    css: ../styles.css
    toc: true
    number-sections: false
    code-fold: true

execute:
  engine: jupyter
  freeze: auto

jupyter: python3