<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.7.21">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="GitSAM">
<meta name="dcterms.date" content="2025-03-08">
<meta name="keywords" content="equivalent martingale measure, equal education opportunity">

<title>Market Price of Education – GitSAM</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js" type="module"></script>
<script src="site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-b2bd955b7378b94aa8c2ba4fafa553c9.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap-bb5f9278568ae542f8467bdb635b70ac.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-sidebar floating nav-fixed quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title"><a href="../index.html">GitSAM</a></span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-papers" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Papers</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-papers">    
        <li>
    <a class="dropdown-item" href="./index.html">
 <span class="dropdown-text">Working</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="./../paper-tbtf/index.qmd">
 <span class="dropdown-text">TBTF</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-books" role="link" data-bs-toggle="dropdown" aria-expanded="false">
 <span class="menu-text">Books</span>
    </a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-books">    
        <li>
    <a class="dropdown-item" href="./../book-gitsam-stats/index.qmd">
 <span class="dropdown-text">gitsam 기초통계학</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="https://primenumbersam.github.io/">
 <span class="dropdown-text">AI 응용 선형대수학</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="https://github.com/primenumbersam/"> 
<span class="menu-text">Apps</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="https://www.gitsam.com"> 
<span class="menu-text">스터디클럽</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools tools-wide">
    <a href="https://laroe.co.kr/" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-shop"></i></a>
    <a href="https://www.youtube.com/@primenumbersam" title="" class="quarto-navigation-tool px-1" aria-label=""><i class="bi bi-youtube"></i></a>
    <div class="dropdown">
      <a href="" title="" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label=""><i class="bi bi-github"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="https://github.com/primenumbersam/primenumbersam.github.io">
            Source Code
            </a>
          </li>
          <li>
            <a class="dropdown-item quarto-navbar-tools-item" href="mailto:primenumbersam@gmail.com">
            Report a Bug
            </a>
          </li>
      </ul>
    </div>
</div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./gitsam_reading.html">경제</a></li><li class="breadcrumb-item"><a href="./pricing_equal.html">Market Price of Education</a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">GitSAM 교육+연구</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">경제</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./gitsam_reading.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">gitsam 독후감</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./indicator_growth.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">경제성장 대표지표?</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./labor_decoupling.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">노동: 기여 vs.&nbsp;분배</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regressions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">From Linear to Curved Structures to Fit the Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pareto_index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Modeling Wealth Distribution</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./gilded_age.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">New Gilded Age</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./modern_matthew.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Modern Matthew Effect</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./dichotomy.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Identifying Dichotomy</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./pricing_equal.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Market Price of Education</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./corner_solution.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Corner Solutions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./market_conditions.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Free Market Conditions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./market_incomplete.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Incomplete Markets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./structure_cointegration.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Time-Varying Cointegration</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./structure_tfp.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Time-varying TFP</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">금융</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./yield_curve.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Yield curve</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./correlation_crypto.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Correlation in Cryptos</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./finance_asset_puzzle.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Asset Premium Puzzles</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./finance_linear.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Linear Models of Finance</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./finance_existence.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Rethinking Asset Existence</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./capm.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Revisiting the CAPM</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./capm_industry.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Industry CAPM</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">돈의 동역학</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./d_overview.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AI시대 자본과 노동</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./d_1_critique.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">주류경제학 비판</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./d_2_elementary.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">동역학 기초수학</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./d_3_model.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AI시대 동역학 모형</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./d_4_ethics.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">AI시대 경제윤리</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#literature-review" id="toc-literature-review" class="nav-link" data-scroll-target="#literature-review"><span class="header-section-number">2</span> Literature Review</a></li>
  <li><a href="#structural-model-of-opportunity-valuation" id="toc-structural-model-of-opportunity-valuation" class="nav-link" data-scroll-target="#structural-model-of-opportunity-valuation"><span class="header-section-number">3</span> Structural Model of Opportunity Valuation</a>
  <ul class="collapse">
  <li><a href="#social-stratification-and-inherited-access" id="toc-social-stratification-and-inherited-access" class="nav-link" data-scroll-target="#social-stratification-and-inherited-access"><span class="header-section-number">3.1</span> Social Stratification and Inherited Access</a></li>
  <li><a href="#emm-and-the-qualification-as-a-call-option" id="toc-emm-and-the-qualification-as-a-call-option" class="nav-link" data-scroll-target="#emm-and-the-qualification-as-a-call-option"><span class="header-section-number">3.2</span> EMM and the Qualification as a Call Option</a></li>
  <li><a href="#empirical-valuation-across-classes" id="toc-empirical-valuation-across-classes" class="nav-link" data-scroll-target="#empirical-valuation-across-classes"><span class="header-section-number">3.3</span> Empirical Valuation Across Classes</a></li>
  <li><a href="#structural-implications" id="toc-structural-implications" class="nav-link" data-scroll-target="#structural-implications"><span class="header-section-number">3.4</span> Structural Implications</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">3.5</span> Conclusion</a></li>
  </ul></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="pricing_equal.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./gitsam_reading.html">경제</a></li><li class="breadcrumb-item"><a href="./pricing_equal.html">Market Price of Education</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Market Price of Education</h1>
<p class="subtitle lead">The seemingly Equal Opportunities under Structural Inequality</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>GitSAM </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 8, 2025</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    This study models the unequal valuation of educational qualifications in stratified economic systems. While educational standards appear uniform across classes, their realized economic value diverges due to inherited capital and opportunity access. We formalize this divergence by applying the Equivalent Martingale Measure (EMM) framework to a two-class model - the proletariat, who access general opportunities, and the capitalist class, who additionally access exclusive ones. In this model, capital constraints create structural “limits to arbitrage” between opportunity sets, embedding inequality into the very fabric of intergenerational mobility. We conceptualize educational qualifications as the strike price in an intergenerational call option - a child may claim inherited capital only upon satisfying a minimum educational standard. We quantify the differential option value of education across classes and interpret this as a measure of structural inefficiency in equal opportunity narratives.
  </div>
</div>

<div>
  <div class="keywords">
    <div class="block-title">Keywords</div>
    <p>equivalent martingale measure, equal education opportunity</p>
  </div>
</div>

</header>


<section id="introduction" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introduction"><span class="header-section-number">1</span> Introduction</h2>
<p>In economically stratified societies, opportunities presented as equal—such as access to education or standardized qualifications—often yield vastly unequal outcomes across social classes. This paradox arises not from individual differences in merit, but from structural disparities in access to capital, networks, and strategic opportunities. As a result, the same formal credential may function as a gateway to ownership and control for one class, and to employment and dependency for another.</p>
<p>While much of financial economics has focused on mispricings in asset markets, we consider an analogous but underexplored domain: the misvaluation of social opportunities under conditions of inherited inequality. In particular, we examine how intergenerational capital endowments determine the realized value of ostensibly equal qualifications.</p>
<p>To formalize this idea, we introduce a stylized model in which society is divided into two economic classes: the proletariat (P) and the capitalist (C). Members of both classes must meet an identical qualification standard (e.g., educational attainment) to realize their economic inheritance. However, the assets they stand to inherit differ fundamentally. While the capitalist class passes down productive capital and exclusive access to high-value opportunities, the proletariat transfers only general access to labor markets. In this framework, the qualification standard operates analogously to a strike price (<span class="math inline">\(K\)</span>) in a call option: it must be met before the holder can claim the underlying asset.</p>
<p>We argue that this metaphor captures a critical structural asymmetry. Even when the qualification threshold is formally equal, the option value of meeting that threshold is class-contingent. The resulting inequality is not a failure of access, but a mispricing of opportunity rooted in structural capital segmentation. Our model offers a formal interpretation of this mechanism, drawing from asset pricing logic—specifically the Equivalent Martingale Measure (EMM)—to quantify how inherited capital shapes the payoff structure of educational credentials.</p>
</section>
<section id="literature-review" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="literature-review"><span class="header-section-number">2</span> Literature Review</h2>
<p>The theoretical foundation of this study builds on the <em>limits to arbitrage</em> framework articulated by <span class="citation" data-cites="shleifer1997limits">Shleifer and Vishny (<a href="#ref-shleifer1997limits" role="doc-biblioref">1997</a>)</span>, which departs from textbook descriptions of riskless, capital-free arbitrage. In reality, most arbitrage is conducted by specialized professionals who manage other people’s capital. This agency relationship introduces a key fragility: interim losses—even in positions with positive expected returns—can lead principals to withdraw funding, forcing premature liquidation. As a result, arbitrage fails not simply due to capital constraints, but because of institutional frictions, reputational risk, and moral hazard embedded in the principal-agent structure. <span class="citation" data-cites="gromb2002equilibrium">Gromb and Vayanos (<a href="#ref-gromb2002equilibrium" role="doc-biblioref">2002</a>)</span> further formalize how capital-constrained arbitrageurs under agency costs produce persistent mispricings with adverse welfare implications. Complementary work by <span class="citation" data-cites="xiong2001convergence">Xiong (<a href="#ref-xiong2001convergence" role="doc-biblioref">2001</a>)</span> emphasizes that convergence trades can be destabilized when arbitrageurs face redemption risks and cannot extend their positions during periods of amplified mispricing.</p>
<p><span class="citation" data-cites="geanakoplos2010leverage">Geanakoplos (<a href="#ref-geanakoplos2010leverage" role="doc-biblioref">2010</a>)</span> contributes the concept of the <strong>leverage cycle</strong>, in which shifts in capital availability and margin requirements not only amplify financial volatility, but also entrench inequality. These dynamics resonate with the structural mechanisms examined in this paper, where economic opportunity is a function of both capital access and intertemporal credibility.</p>
<p>Behavioral finance research, as surveyed by <span class="citation" data-cites="barberis2003survey">Barberis and Thaler (<a href="#ref-barberis2003survey" role="doc-biblioref">2003</a>)</span>, highlights how cognitive biases and non-Bayesian updating further limit arbitrage effectiveness. These behavioral frictions—when coupled with institutional rigidities—exacerbate price anomalies and contribute to enduring structural barriers in economic mobility.</p>
<p>Beyond finance, sociological theories and applied economic studies shed light on the broader mechanisms of <strong>structural inequality</strong>. Bourdieu’s theory of <strong>social reproduction</strong> <span class="citation" data-cites="bourdieu1973cultural">Bourdieu (<a href="#ref-bourdieu1973cultural" role="doc-biblioref">1973</a>)</span> posits that cultural capital—acquired through family and class—perpetuates unequal opportunity across generations. Empirical work by <span class="citation" data-cites="chetty2014family">Chetty et al. (<a href="#ref-chetty2014family" role="doc-biblioref">2014</a>)</span> establishes a strong linkage between parental income and children’s educational and labor market outcomes, confirming that equal qualifications yield vastly unequal economic returns depending on class background. <span class="citation" data-cites="piketty2014capital">Piketty (<a href="#ref-piketty2014capital" role="doc-biblioref">2014</a>)</span> emphasizes that capital accumulation and intergenerational wealth transfers dominate earned income in determining long-term economic trajectories.</p>
<p>Recent reports by the UK’s Social Mobility Commission <span class="citation" data-cites="smc2023class">Social Mobility Commission (<a href="#ref-smc2023class" role="doc-biblioref">2023</a>)</span> and the OECD <span class="citation" data-cites="oecd2018mobility">OECD (<a href="#ref-oecd2018mobility" role="doc-biblioref">2018</a>)</span> corroborate this view, showing that economic mobility has stagnated despite rising access to education. <span class="citation" data-cites="reeves2017glassfloor">Reeves (<a href="#ref-reeves2017glassfloor" role="doc-biblioref">2017</a>)</span> introduces the concept of the <strong>“glass floor”</strong>, where the upper class protects its status not by accelerating upward mobility but by shielding itself from downward mobility—often through mechanisms such as inherited networks, cultural signaling, and capital buffers.</p>
<p>Together, these literatures converge on a central insight: <strong>nominally equal qualifications can mask radically unequal opportunity valuations</strong>, shaped by capital endowments, behavioral constraints, and institutional structures. This study extends the literature by providing a formal asset pricing model in which educational qualifications function as <strong>strike prices</strong> in class-contingent call options on inherited capital. The framework quantifies how structurally identical credentials yield asymmetric economic outcomes, offering a new perspective on the market valuation of education under inequality.</p>
</section>
<section id="structural-model-of-opportunity-valuation" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="structural-model-of-opportunity-valuation"><span class="header-section-number">3</span> Structural Model of Opportunity Valuation</h2>
<section id="social-stratification-and-inherited-access" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="social-stratification-and-inherited-access"><span class="header-section-number">3.1</span> Social Stratification and Inherited Access</h3>
<p>We consider a stylized economy consisting of two economically segregated classes:</p>
<ul>
<li>Proletariat (P): Access only to general economic opportunities.</li>
<li>Capitalist (C): Access to both general and exclusive special opportunities.</li>
</ul>
<p>Within each class, opportunities are traded in perfectly competitive markets that satisfy the no-arbitrage condition internally. However, capital constraints prevent members of the proletariat from accessing the exclusive opportunities available to the capitalist class. This segmentation effectively enforces a limit to arbitrage between classes, rendering superior opportunities inaccessible to the working class.</p>
<p>From a pricing perspective, while special opportunities may have equal or higher intrinsic value than general ones, their inaccessibility to the proletariat implies a market inefficiency rooted in capital immobility. In theory, the capitalist class might profit by arbitraging—shorting general opportunities and longing special ones. However, such trades require the existence of a counterparty market for general opportunities. In this stratified economy, such a market is absent: general opportunities, often tied to future labor or positional access, are not formally tradable. Hence, arbitrage fails not due to capital constraints, but due to market incompleteness.</p>
<p>Both classes transmit economic outcomes across generations. However, children must meet a common qualification threshold (e.g., educational degree) before they can claim their inherited assets. This threshold functions as a strike price (<span class="math inline">\(K\)</span>) in a call option: until it is met, the offspring hold a contingent claim—a call option—on their parents’ accumulated capital.</p>
<p>Crucially, although the qualification standard is uniform, its realized economic payoff differs dramatically. A graduate from the capitalist class inherits and operates substantial capital, while a similarly qualified graduate from the proletariat class becomes an employee within capitalist-owned institutions.</p>
<p>This section formalizes the option-like structure of intergenerational mobility, where equal credentials mask deeply unequal access to capital. The goal is to quantify this asymmetry through a structural valuation framework based on asset pricing theory.</p>
</section>
<section id="emm-and-the-qualification-as-a-call-option" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="emm-and-the-qualification-as-a-call-option"><span class="header-section-number">3.2</span> EMM and the Qualification as a Call Option</h3>
<p>We consider a stylized one-period binomial framework with two possible future states—good (up) and bad (down). This minimal setting allows us to derive the present value of a <strong>call option</strong> under the <strong>Equivalent Martingale Measure (EMM)</strong>. Under EMM, asset prices discounted at the risk-free rate evolve as martingales in a risk-neutral world, ensuring no-arbitrage pricing.</p>
<p>Let <span class="math inline">\(S_0\)</span> denote the current value of an asset and <span class="math inline">\(R\)</span> the gross risk-free return over the period. Then the value of a European call option with strike price <span class="math inline">\(K\)</span> at time 0, denoted <span class="math inline">\(\hat{f}_0\)</span>, satisfies:</p>
<p><span class="math display">\[
\hat{f}_0 \cdot R = \mathbb{E}^q[f_1]
\]</span></p>
<p>where the terminal payoff is:</p>
<p><span class="math display">\[
f_1 = \max(S_0 \cdot U - K, 0)
\]</span></p>
<p>with <span class="math inline">\(U\)</span> representing the up-state return. The EMM condition for the underlying asset implies:</p>
<p><span class="math display">\[
S_0 \cdot R = \mathbb{E}^q[S_1]
\]</span></p>
<p>Solving for the <strong>state price density</strong> (risk-neutral probability) <span class="math inline">\(q\)</span> yields:</p>
<p><span class="math display">\[
q = \frac{R - D}{U - D}
\]</span></p>
<p>Assuming the following normalization and notation:</p>
<ul>
<li>Initial Asset Price: <span class="math inline">\(S_0 = 1\)</span></li>
<li>Strike Price (qualification threshold): <span class="math inline">\(K = 1\)</span></li>
<li>Up-state return: <span class="math inline">\(U\)</span></li>
<li>Down-state return: <span class="math inline">\(D\)</span></li>
<li>Gross risk-free return: <span class="math inline">\(R\)</span></li>
<li>Maturity: 18 years (quarterly steps = 72 periods)</li>
</ul>
<p>we derive the fair value of the option as:</p>
<p><span class="math display">\[
\hat{f}_0 = \frac{(R - D)(U - 1)}{R(U - D)}
\]</span></p>
<p>This expression quantifies the present value of a future <strong>qualification-based claim</strong>, where the payoff depends on surpassing a common educational or institutional threshold. Crucially, while the strike price <span class="math inline">\(K\)</span> is identical across individuals, the valuation of the option varies across economic classes, depending on the underlying asset and pricing measure.</p>
<p>In our broader framework, the <strong>underlying asset differs by class</strong>:</p>
<ul>
<li>For the <strong>proletariat class (P)</strong>, the risky asset is interpreted as human capital, with its return distribution proxied by wage growth rate. Their risk-free rate is taken to be the growth rate of real GDP per capita, reflecting limited access to financial instruments.</li>
<li>For the <strong>capitalist class (C)</strong>, the risky asset corresponds to equity (e.g., stock ownership), and the risk-free asset is approximated by long-term bond yields. Unlike P class, the C class has access to capital markets and can realize financial returns conditional on qualifications.</li>
</ul>
<p>Although a continuous-time limit (e.g., Black-Scholes under <span class="math inline">\(U \cdot D = 1\)</span>) could be adopted, we retain the discrete binomial structure for its interpretability and ability to directly compare inter-class valuation asymmetries. The model makes transparent how <strong>seemingly equal qualifications can yield divergent option values</strong>, driven by class-specific capital endowments and asset accessibility.</p>
</section>
<section id="empirical-valuation-across-classes" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="empirical-valuation-across-classes"><span class="header-section-number">3.3</span> Empirical Valuation Across Classes</h3>
<p>To quantify the asymmetry in opportunity valuation across social classes, we empirically estimate the EMM-based call option values for the proletariat and capitalist classes using historical U.S. data from Q1 1982 to Q4 2019 (152 quarterly observations). For each class, we identify distinct risky and risk-free asset proxies, reflecting their differential access to economic instruments.</p>
<p><strong>For Proletariat (P) Class Children:</strong></p>
<ul>
<li>Return on <strong>Risky Asset</strong>: growth rate of U.S. Median usual weekly real earnings (LES1252881600Q)</li>
<li>Return on <strong>Risk-Free Asset</strong>: growth rate of U.S. Real GDP per capita (A939RX0Q048SBEA)</li>
<li><strong>Estimated Parameters</strong>:
<ul>
<li><span class="math inline">\(U_p\)</span>: 75th percentile of quarterly wage growth</li>
<li><span class="math inline">\(D_p\)</span>: 25th percentile of quarterly wage growth</li>
<li><span class="math inline">\(R_p\)</span>: Median quarterly growth rate of real GDP per capita</li>
</ul></li>
</ul>
<p><strong>For Capitalist (C) Class Children:</strong></p>
<ul>
<li>Return on <strong>Risky Asset</strong>: growth rate of S&amp;P 500 Total Return Index (SPX)</li>
<li>Return on <strong>Risk-Free Asset</strong>: 10-Year U.S. Treasury Bond Yield (DGS10)</li>
<li><strong>Estimated Parameters</strong>:
<ul>
<li><span class="math inline">\(U_c\)</span>: 75th percentile of equity return</li>
<li><span class="math inline">\(D_c\)</span>: 25th percentile of equity return</li>
<li><span class="math inline">\(R_c\)</span>:= Median of quarterly US 10-Year Treasury Bond Yield</li>
</ul></li>
</ul>
<p>We now compute and compare <span class="math inline">\(\hat{f}_0\)</span> for each class.</p>
<div id="988415a5" class="cell" data-execution_count="1">
<div class="cell-output cell-output-stdout">
<pre><code>Proletariat Class Children Parameters:
U_p: 1.0060
D_p: 0.9968
R_p: 1.0051

Capitalist Class Children Parameters:
U_c: 1.0711
D_c: 0.9916
R_c: 1.0514

Fair price of Call Option, held by Proletariat Class Children:
 0.3043
Fair price of Call Option, held by Capitalist Class Children:
 0.9728</code></pre>
</div>
</div>
<div id="b272a88c" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div>
<figure class="figure">
<p><img src="pricing_equal_files/figure-html/cell-3-output-1.png" class="img-fluid figure-img"></p>
</figure>
</div>
</div>
</div>
<p>As <span class="math inline">\(U\)</span> rises, improvements in <span class="math inline">\(D\)</span> drive option values faster, reflecting how convex opportunity structures magnify marginal safety. This highlights the asymmetry in asset-based opportunity structures—capitalist-class children benefit not only from better average returns, but also from a sharper convex payoff structure that amplifies improvements across all economic states.</p>
</section>
<section id="structural-implications" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="structural-implications"><span class="header-section-number">3.4</span> Structural Implications</h3>
<p>Empirical estimation reveals a stark asymmetry in the valuation of identical qualification thresholds across classes. The EMM-based fair value of the call option for proletariat-class children is approximately <code>0.3043</code>, while for capitalist-class children it is <code>0.9728</code> — a more than threefold difference.</p>
<p>This disparity does not stem from differences in effort or merit, but from structurally unequal asset endowments and access to opportunity. In our framework, the same strike price <span class="math inline">\(K = 1\)</span> results in class-specific valuations due to differing <span class="math inline">\((U, D, R)\)</span> parameters. The qualification thus operates not as a universal gateway, but as a <strong>contingent claim whose value is conditioned by class</strong>.</p>
<p>This structural valuation gap challenges the premise of equal opportunity and underscores how asset-based class differentiation shapes the realized value of seemingly identical credentials. Our framework calls for a reassessment of how economic policy, educational equity, and social mobility are understood and modeled <strong>under persistent inequality</strong>.</p>
</section>
<section id="conclusion" class="level3" data-number="3.5">
<h3 data-number="3.5" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">3.5</span> Conclusion</h3>
<p>This paper reframes education not as an equalizing force, but as an <strong>option contract on inherited capital</strong>—one whose value varies sharply across economic classes. When access to assets and opportunity is structurally segmented, qualifications lose their universal function and become class-contingent claims. The findings highlight the need to rethink educational fairness, not merely in terms of formal access, but through the lens of the payoff structures such access yields in unequal economic environments.</p>



</section>
</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-barberis2003survey" class="csl-entry" role="listitem">
Barberis, Nicholas, and Richard Thaler. 2003. <span>“A Survey of Behavioral Finance.”</span> <em>Handbook of the Economics of Finance</em> 1: 1053–1128.
</div>
<div id="ref-bourdieu1973cultural" class="csl-entry" role="listitem">
Bourdieu, Pierre. 1973. <span>“Cultural Reproduction and Social Reproduction,”</span> 71–112.
</div>
<div id="ref-chetty2014family" class="csl-entry" role="listitem">
Chetty, Raj, Nathaniel Hendren, Patrick Kline, and Emmanuel Saez. 2014. <span>“Where Is the Land of Opportunity? The Geography of Intergenerational Mobility in the United States.”</span> <em>Quarterly Journal of Economics</em> 129 (4): 1553–623.
</div>
<div id="ref-geanakoplos2010leverage" class="csl-entry" role="listitem">
Geanakoplos, John. 2010. <span>“The Leverage Cycle.”</span> <em>NBER Macroeconomics Annual</em> 24: 1–65.
</div>
<div id="ref-gromb2002equilibrium" class="csl-entry" role="listitem">
Gromb, Denis, and Dimitri Vayanos. 2002. <span>“Equilibrium and Welfare in Markets with Financially Constrained Arbitrageurs.”</span> <em>Journal of Financial Economics</em> 66 (2-3): 361–407.
</div>
<div id="ref-oecd2018mobility" class="csl-entry" role="listitem">
OECD. 2018. <span>“A Broken Social Elevator? How to Promote Social Mobility.”</span> OECD Publishing. <a href="https://www.oecd.org/social/social-mobility-2018-report.pdf">https://www.oecd.org/social/social-mobility-2018-report.pdf</a>.
</div>
<div id="ref-piketty2014capital" class="csl-entry" role="listitem">
Piketty, Thomas. 2014. <em>Capital in the Twenty-First Century</em>. Harvard University Press.
</div>
<div id="ref-reeves2017glassfloor" class="csl-entry" role="listitem">
Reeves, Richard V. 2017. <em>Dream Hoarders: How the American Upper Middle Class Is Leaving Everyone Else in the Dust</em>. Brookings Institution Press.
</div>
<div id="ref-shleifer1997limits" class="csl-entry" role="listitem">
Shleifer, Andrei, and Robert W. Vishny. 1997. <span>“The Limits of Arbitrage.”</span> <em>The Journal of Finance</em> 52 (1): 35–55.
</div>
<div id="ref-smc2023class" class="csl-entry" role="listitem">
Social Mobility Commission. 2023. <span>“State of the Nation Report 2023: Class, Meritocracy and Inequality.”</span> <em>UK Government Publication</em>. <a href="https://www.gov.uk/government/publications/social-mobility-commission-2023-report">https://www.gov.uk/government/publications/social-mobility-commission-2023-report</a>.
</div>
<div id="ref-xiong2001convergence" class="csl-entry" role="listitem">
Xiong, Wei. 2001. <span>“Convergence Trading with Wealth Effects.”</span> <em>Journal of Financial Economics</em> 62 (2): 247–92.
</div>
</div></section><section class="quarto-appendix-contents" id="quarto-reuse"><h2 class="anchored quarto-appendix-heading">Reuse</h2><div class="quarto-appendix-contents"><div><a rel="license" href="https://creativecommons.org/licenses/by-nc-sa/4.0/">CC BY-NC-SA 4.0</a></div></div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
        const codeEl = trigger.previousElementSibling.cloneNode(true);
        for (const childEl of codeEl.children) {
          if (isCodeAnnotation(childEl)) {
            childEl.remove();
          }
        }
        return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>